/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSOFAITEMFIELDS_H_
#define _OSGSOFAITEMFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGVCoREItemSofaDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

class SofaItem;

OSG_GEN_CONTAINERPTR(SofaItem);

VCORE_END_NAMESPACE

OSG_BEGIN_NAMESPACE

VCORE_IMPORT_NAMESPACE;
/*! \ingroup GrpVCoreSystemFieldTraits
    \ingroup GrpLibOSGVCoREItemSofa
 */
template <>
struct FieldTraits<SofaItem *, nsVCoRE> :
    public FieldTraitsFCPtrBase<SofaItem *, nsVCoRE>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<SofaItem *, nsVCoRE>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCOREITEMSOFA_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<SofaItem *, nsVCoRE>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecSofaItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<SofaItem *, nsVCoRE>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecSofaItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<SofaItem *, nsVCoRE>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakSofaItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<SofaItem *, nsVCoRE>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdSofaItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<SofaItem *, nsVCoRE>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecSofaItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<SofaItem *, nsVCoRE>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecSofaItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<SofaItem *, nsVCoRE>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakSofaItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<SofaItem *, nsVCoRE>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdSofaItemPtr"; 
}


OSG_END_NAMESPACE

VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<SofaItem *,
                      RecordedRefCountPolicy, nsVCoRE  > SFRecSofaItemPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<SofaItem *,
                      UnrecordedRefCountPolicy, nsVCoRE> SFUnrecSofaItemPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<SofaItem *,
                      WeakRefCountPolicy, nsVCoRE      > SFWeakSofaItemPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<SofaItem *,
                      NoRefCountPolicy, nsVCoRE        > SFUncountedSofaItemPtr;


/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<SofaItem *,
                      RecordedRefCountPolicy, nsVCoRE  > MFRecSofaItemPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<SofaItem *,
                      UnrecordedRefCountPolicy, nsVCoRE> MFUnrecSofaItemPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<SofaItem *,
                      WeakRefCountPolicy, nsVCoRE      > MFWeakSofaItemPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<SofaItem *,
                      NoRefCountPolicy, nsVCoRE        > MFUncountedSofaItemPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoREItemSofa */
struct SFRecSofaItemPtr : 
    public PointerSField<SofaItem *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoREItemSofa */
struct SFUnrecSofaItemPtr : 
    public PointerSField<SofaItem *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoREItemSofa */
struct SFWeakSofaItemPtr :
    public PointerSField<SofaItem *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoREItemSofa */
struct SFUncountedSofaItemPtr :
    public PointerSField<SofaItem *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoREItemSofa */
struct MFRecSofaItemPtr :
    public PointerMField<SofaItem *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoREItemSofa */
struct MFUnrecSofaItemPtr :
    public PointerMField<SofaItem *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoREItemSofa */
struct MFWeakSofaItemPtr :
    public PointerMField<SofaItem *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoREItemSofa */
struct MFUncountedSofaItemPtr :
    public PointerMField<SofaItem *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

VCORE_END_NAMESPACE

#endif /* _OSGSOFAITEMFIELDS_H_ */
