/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGVCDYNFIELDCONTAINERFIELDS_H_
#define _OSGVCDYNFIELDCONTAINERFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGVCoREBaseDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

class VCDynFieldContainer;

OSG_GEN_CONTAINERPTR(VCDynFieldContainer);

VCORE_END_NAMESPACE

OSG_BEGIN_NAMESPACE

VCORE_IMPORT_NAMESPACE;
/*! \ingroup GrpVCoreBaseFieldTraits
    \ingroup GrpLibOSGVCoREBase
 */
template <>
struct FieldTraits<VCDynFieldContainer *, nsVCoRE> :
    public FieldTraitsFCPtrBase<VCDynFieldContainer *, nsVCoRE>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<VCDynFieldContainer *, nsVCoRE>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCOREBASE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<VCDynFieldContainer *, nsVCoRE>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecVCDynFieldContainerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCDynFieldContainer *, nsVCoRE>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecVCDynFieldContainerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCDynFieldContainer *, nsVCoRE>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakVCDynFieldContainerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCDynFieldContainer *, nsVCoRE>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdVCDynFieldContainerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCDynFieldContainer *, nsVCoRE>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecVCDynFieldContainerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCDynFieldContainer *, nsVCoRE>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecVCDynFieldContainerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCDynFieldContainer *, nsVCoRE>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakVCDynFieldContainerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCDynFieldContainer *, nsVCoRE>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdVCDynFieldContainerPtr"; 
}


OSG_END_NAMESPACE

VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVCoreBaseFieldSFields */
typedef PointerSField<VCDynFieldContainer *,
                      RecordedRefCountPolicy, nsVCoRE  > SFRecVCDynFieldContainerPtr;
/*! \ingroup GrpVCoreBaseFieldSFields */
typedef PointerSField<VCDynFieldContainer *,
                      UnrecordedRefCountPolicy, nsVCoRE> SFUnrecVCDynFieldContainerPtr;
/*! \ingroup GrpVCoreBaseFieldSFields */
typedef PointerSField<VCDynFieldContainer *,
                      WeakRefCountPolicy, nsVCoRE      > SFWeakVCDynFieldContainerPtr;
/*! \ingroup GrpVCoreBaseFieldSFields */
typedef PointerSField<VCDynFieldContainer *,
                      NoRefCountPolicy, nsVCoRE        > SFUncountedVCDynFieldContainerPtr;


/*! \ingroup GrpVCoreBaseFieldMFields */
typedef PointerMField<VCDynFieldContainer *,
                      RecordedRefCountPolicy, nsVCoRE  > MFRecVCDynFieldContainerPtr;
/*! \ingroup GrpVCoreBaseFieldMFields */
typedef PointerMField<VCDynFieldContainer *,
                      UnrecordedRefCountPolicy, nsVCoRE> MFUnrecVCDynFieldContainerPtr;
/*! \ingroup GrpVCoreBaseFieldMFields */
typedef PointerMField<VCDynFieldContainer *,
                      WeakRefCountPolicy, nsVCoRE      > MFWeakVCDynFieldContainerPtr;
/*! \ingroup GrpVCoreBaseFieldMFields */
typedef PointerMField<VCDynFieldContainer *,
                      NoRefCountPolicy, nsVCoRE        > MFUncountedVCDynFieldContainerPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpVCoreBaseFieldSFields \ingroup GrpLibOSGVCoREBase */
struct SFRecVCDynFieldContainerPtr : 
    public PointerSField<VCDynFieldContainer *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreBaseFieldSFields \ingroup GrpLibOSGVCoREBase */
struct SFUnrecVCDynFieldContainerPtr : 
    public PointerSField<VCDynFieldContainer *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreBaseFieldSFields \ingroup GrpLibOSGVCoREBase */
struct SFWeakVCDynFieldContainerPtr :
    public PointerSField<VCDynFieldContainer *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVCoreBaseFieldSFields \ingroup GrpLibOSGVCoREBase */
struct SFUncountedVCDynFieldContainerPtr :
    public PointerSField<VCDynFieldContainer *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVCoreBaseFieldMFields \ingroup GrpLibOSGVCoREBase */
struct MFRecVCDynFieldContainerPtr :
    public PointerMField<VCDynFieldContainer *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVCoreBaseFieldMFields \ingroup GrpLibOSGVCoREBase */
struct MFUnrecVCDynFieldContainerPtr :
    public PointerMField<VCDynFieldContainer *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreBaseFieldMFields \ingroup GrpLibOSGVCoREBase */
struct MFWeakVCDynFieldContainerPtr :
    public PointerMField<VCDynFieldContainer *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVCoreBaseFieldMFields \ingroup GrpLibOSGVCoREBase */
struct MFUncountedVCDynFieldContainerPtr :
    public PointerMField<VCDynFieldContainer *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

VCORE_END_NAMESPACE

#endif /* _OSGVCDYNFIELDCONTAINERFIELDS_H_ */
