/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGITEMFIELDS_H_
#define _OSGITEMFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGVCoREBaseDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

class Item;

OSG_GEN_CONTAINERPTR(Item);

VCORE_END_NAMESPACE

OSG_BEGIN_NAMESPACE

VCORE_IMPORT_NAMESPACE;
/*! \ingroup GrpVCoREBaseFieldTraits
    \ingroup GrpLibOSGVCoREBase
 */
template <>
struct FieldTraits<Item *, nsVCoRE> :
    public FieldTraitsFCPtrBase<Item *, nsVCoRE>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<Item *, nsVCoRE>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCOREBASE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<Item *, nsVCoRE>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<Item *, nsVCoRE>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<Item *, nsVCoRE>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<Item *, nsVCoRE>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<Item *, nsVCoRE>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<Item *, nsVCoRE>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<Item *, nsVCoRE>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<Item *, nsVCoRE>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdItemPtr"; 
}


/*! \ingroup GrpVCoREBaseFieldTraits
 */
template <>
struct FieldTraits<Item *, nsVCoRE + 1> :
    public FieldTraitsFCPtrBase<Item *, nsVCoRE + 1>
{
  private:

  public:
    typedef FieldTraits<Item *, nsVCoRE + 1>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCOREBASE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);
};

template<> inline
const Char8 *FieldTraits<Item *, nsVCoRE + 1>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecChildItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<Item *, nsVCoRE + 1>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecChildItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<Item *, nsVCoRE + 1>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakChildItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<Item *, nsVCoRE + 1>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdChildItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<Item *, nsVCoRE + 1>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecChildItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<Item *, nsVCoRE + 1>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecChildItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<Item *, nsVCoRE + 1>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakChildItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<Item *, nsVCoRE + 1>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdChildItemPtr"; 
}


OSG_END_NAMESPACE

VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVCoREBaseFieldSFields */
typedef PointerSField<Item *,
                      RecordedRefCountPolicy, nsVCoRE  > SFRecItemPtr;
/*! \ingroup GrpVCoREBaseFieldSFields */
typedef PointerSField<Item *,
                      UnrecordedRefCountPolicy, nsVCoRE> SFUnrecItemPtr;
/*! \ingroup GrpVCoREBaseFieldSFields */
typedef PointerSField<Item *,
                      WeakRefCountPolicy, nsVCoRE      > SFWeakItemPtr;
/*! \ingroup GrpVCoREBaseFieldSFields */
typedef PointerSField<Item *,
                      NoRefCountPolicy, nsVCoRE        > SFUncountedItemPtr;


/*! \ingroup GrpVCoREBaseFieldMFields */
typedef PointerMField<Item *,
                      RecordedRefCountPolicy, nsVCoRE  > MFRecItemPtr;
/*! \ingroup GrpVCoREBaseFieldMFields */
typedef PointerMField<Item *,
                      UnrecordedRefCountPolicy, nsVCoRE> MFUnrecItemPtr;
/*! \ingroup GrpVCoREBaseFieldMFields */
typedef PointerMField<Item *,
                      WeakRefCountPolicy, nsVCoRE      > MFWeakItemPtr;
/*! \ingroup GrpVCoREBaseFieldMFields */
typedef PointerMField<Item *,
                      NoRefCountPolicy, nsVCoRE        > MFUncountedItemPtr;



/*! \ingroup GrpVCoREBaseFieldSFields */
typedef ChildPointerSField<
          Item *, 
          UnrecordedRefCountPolicy,
          nsVCoRE + 1             > SFUnrecChildItemPtr;


/*! \ingroup GrpVCoREBaseFieldMFields */
typedef ChildPointerMField<
          Item *, 
          UnrecordedRefCountPolicy,
          nsVCoRE + 1             > MFUnrecChildItemPtr;



#else // these are the doxygen hacks

/*! \ingroup GrpVCoREBaseFieldSFields \ingroup GrpLibOSGVCoREBase */
struct SFRecItemPtr : 
    public PointerSField<Item *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVCoREBaseFieldSFields \ingroup GrpLibOSGVCoREBase */
struct SFUnrecItemPtr : 
    public PointerSField<Item *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoREBaseFieldSFields \ingroup GrpLibOSGVCoREBase */
struct SFWeakItemPtr :
    public PointerSField<Item *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVCoREBaseFieldSFields \ingroup GrpLibOSGVCoREBase */
struct SFUncountedItemPtr :
    public PointerSField<Item *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVCoREBaseFieldMFields \ingroup GrpLibOSGVCoREBase */
struct MFRecItemPtr :
    public PointerMField<Item *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVCoREBaseFieldMFields \ingroup GrpLibOSGVCoREBase */
struct MFUnrecItemPtr :
    public PointerMField<Item *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoREBaseFieldMFields \ingroup GrpLibOSGVCoREBase */
struct MFWeakItemPtr :
    public PointerMField<Item *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVCoREBaseFieldMFields \ingroup GrpLibOSGVCoREBase */
struct MFUncountedItemPtr :
    public PointerMField<Item *,
                         NoRefCountPolicy        > {};



/*! \ingroup GrpVCoREBaseFieldSFields \ingroup GrpLibOSGVCoREBase */
struct SFUnrecChildItemPtr :
    public ChildPointerSField<
        Item *, 
        UnrecordedRefCountPolicy,
        nsVCoRE + 1             > {};


/*! \ingroup GrpVCoREBaseFieldMFields \ingroup GrpLibOSGVCoREBase */
struct MFUnrecChildItemPtr :
    public ChildPointerMField<
        Item *, 
        UnrecordedRefCountPolicy,
        nsVCoRE + 1             > {};


#endif // these are the doxygen hacks

VCORE_END_NAMESPACE

#endif /* _OSGITEMFIELDS_H_ */
