/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGVCOREITEMFIELDS_H_
#define _OSGVCOREITEMFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGVCoreBaseDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class VCoreItem;

OSG_GEN_CONTAINERPTR(VCoreItem);

/*! \ingroup GrpVCoreBaseFieldTraits
    \ingroup GrpLibOSGVCoreBase
 */
template <>
struct FieldTraits<VCoreItem *> :
    public FieldTraitsFCPtrBase<VCoreItem *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<VCoreItem *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCOREBASE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFVCoreItemPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFVCoreItemPtr"; }
};

template<> inline
const Char8 *FieldTraits<VCoreItem *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecVCoreItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreItem *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecVCoreItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreItem *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakVCoreItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreItem *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdVCoreItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreItem *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecVCoreItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreItem *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecVCoreItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreItem *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakVCoreItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreItem *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdVCoreItemPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVCoreBaseFieldSFields */
typedef PointerSField<VCoreItem *,
                      RecordedRefCountPolicy  > SFRecVCoreItemPtr;
/*! \ingroup GrpVCoreBaseFieldSFields */
typedef PointerSField<VCoreItem *,
                      UnrecordedRefCountPolicy> SFUnrecVCoreItemPtr;
/*! \ingroup GrpVCoreBaseFieldSFields */
typedef PointerSField<VCoreItem *,
                      WeakRefCountPolicy      > SFWeakVCoreItemPtr;
/*! \ingroup GrpVCoreBaseFieldSFields */
typedef PointerSField<VCoreItem *,
                      NoRefCountPolicy        > SFUncountedVCoreItemPtr;


/*! \ingroup GrpVCoreBaseFieldMFields */
typedef PointerMField<VCoreItem *,
                      RecordedRefCountPolicy  > MFRecVCoreItemPtr;
/*! \ingroup GrpVCoreBaseFieldMFields */
typedef PointerMField<VCoreItem *,
                      UnrecordedRefCountPolicy> MFUnrecVCoreItemPtr;
/*! \ingroup GrpVCoreBaseFieldMFields */
typedef PointerMField<VCoreItem *,
                      WeakRefCountPolicy      > MFWeakVCoreItemPtr;
/*! \ingroup GrpVCoreBaseFieldMFields */
typedef PointerMField<VCoreItem *,
                      NoRefCountPolicy        > MFUncountedVCoreItemPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpVCoreBaseFieldSFields \ingroup GrpLibOSGVCoreBase */
struct SFRecVCoreItemPtr : 
    public PointerSField<VCoreItem *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreBaseFieldSFields \ingroup GrpLibOSGVCoreBase */
struct SFUnrecVCoreItemPtr : 
    public PointerSField<VCoreItem *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreBaseFieldSFields \ingroup GrpLibOSGVCoreBase */
struct SFWeakVCoreItemPtr :
    public PointerSField<VCoreItem *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVCoreBaseFieldSFields \ingroup GrpLibOSGVCoreBase */
struct SFUncountedVCoreItemPtr :
    public PointerSField<VCoreItem *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVCoreBaseFieldMFields \ingroup GrpLibOSGVCoreBase */
struct MFRecVCoreItemPtr :
    public PointerMField<VCoreItem *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVCoreBaseFieldMFields \ingroup GrpLibOSGVCoreBase */
struct MFUnrecVCoreItemPtr :
    public PointerMField<VCoreItem *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreBaseFieldMFields \ingroup GrpLibOSGVCoreBase */
struct MFWeakVCoreItemPtr :
    public PointerMField<VCoreItem *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVCoreBaseFieldMFields \ingroup GrpLibOSGVCoreBase */
struct MFUncountedVCoreItemPtr :
    public PointerMField<VCoreItem *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGVCOREITEMFIELDS_H_ */
