/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGVCOREITEMFIELDS_H_
#define _OSGVCOREITEMFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGVCoreBaseDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class VCoreItem;

OSG_GEN_CONTAINERPTR(VCoreItem);
/*! \ingroup GrpVCoreBaseFieldTraits
    \ingroup GrpLibOSGVCoreBase
 */
template <>
struct FieldTraits<VCoreItem *, nsOSG> :
    public FieldTraitsFCPtrBase<VCoreItem *, nsOSG>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<VCoreItem *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCOREBASE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<VCoreItem *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecVCoreItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreItem *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecVCoreItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreItem *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakVCoreItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreItem *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdVCoreItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreItem *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecVCoreItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreItem *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecVCoreItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreItem *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakVCoreItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreItem *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdVCoreItemPtr"; 
}


/*! \ingroup GrpVCoreBaseFieldTraits
 */
template <>
struct FieldTraits<VCoreItem *, nsOSG + 1> :
    public FieldTraitsFCPtrBase<VCoreItem *, nsOSG + 1>
{
  private:

  public:
    typedef FieldTraits<VCoreItem *, nsOSG + 1>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCOREBASE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);
};

template<> inline
const Char8 *FieldTraits<VCoreItem *, nsOSG + 1>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecChildVCoreItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreItem *, nsOSG + 1>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecChildVCoreItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreItem *, nsOSG + 1>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakChildVCoreItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreItem *, nsOSG + 1>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdChildVCoreItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreItem *, nsOSG + 1>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecChildVCoreItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreItem *, nsOSG + 1>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecChildVCoreItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreItem *, nsOSG + 1>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakChildVCoreItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreItem *, nsOSG + 1>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdChildVCoreItemPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVCoreBaseFieldSFields */
typedef PointerSField<VCoreItem *,
                      RecordedRefCountPolicy, nsOSG  > SFRecVCoreItemPtr;
/*! \ingroup GrpVCoreBaseFieldSFields */
typedef PointerSField<VCoreItem *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecVCoreItemPtr;
/*! \ingroup GrpVCoreBaseFieldSFields */
typedef PointerSField<VCoreItem *,
                      WeakRefCountPolicy, nsOSG      > SFWeakVCoreItemPtr;
/*! \ingroup GrpVCoreBaseFieldSFields */
typedef PointerSField<VCoreItem *,
                      NoRefCountPolicy, nsOSG        > SFUncountedVCoreItemPtr;


/*! \ingroup GrpVCoreBaseFieldMFields */
typedef PointerMField<VCoreItem *,
                      RecordedRefCountPolicy, nsOSG  > MFRecVCoreItemPtr;
/*! \ingroup GrpVCoreBaseFieldMFields */
typedef PointerMField<VCoreItem *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecVCoreItemPtr;
/*! \ingroup GrpVCoreBaseFieldMFields */
typedef PointerMField<VCoreItem *,
                      WeakRefCountPolicy, nsOSG      > MFWeakVCoreItemPtr;
/*! \ingroup GrpVCoreBaseFieldMFields */
typedef PointerMField<VCoreItem *,
                      NoRefCountPolicy, nsOSG        > MFUncountedVCoreItemPtr;



/*! \ingroup GrpVCoreBaseFieldSFields */
typedef ChildPointerSField<
          VCoreItem *, 
          UnrecordedRefCountPolicy,
          nsOSG + 1             > SFUnrecChildVCoreItemPtr;


/*! \ingroup GrpVCoreBaseFieldMFields */
typedef ChildPointerMField<
          VCoreItem *, 
          UnrecordedRefCountPolicy,
          nsOSG + 1             > MFUnrecChildVCoreItemPtr;



#else // these are the doxygen hacks

/*! \ingroup GrpVCoreBaseFieldSFields \ingroup GrpLibOSGVCoreBase */
struct SFRecVCoreItemPtr : 
    public PointerSField<VCoreItem *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreBaseFieldSFields \ingroup GrpLibOSGVCoreBase */
struct SFUnrecVCoreItemPtr : 
    public PointerSField<VCoreItem *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreBaseFieldSFields \ingroup GrpLibOSGVCoreBase */
struct SFWeakVCoreItemPtr :
    public PointerSField<VCoreItem *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVCoreBaseFieldSFields \ingroup GrpLibOSGVCoreBase */
struct SFUncountedVCoreItemPtr :
    public PointerSField<VCoreItem *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVCoreBaseFieldMFields \ingroup GrpLibOSGVCoreBase */
struct MFRecVCoreItemPtr :
    public PointerMField<VCoreItem *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVCoreBaseFieldMFields \ingroup GrpLibOSGVCoreBase */
struct MFUnrecVCoreItemPtr :
    public PointerMField<VCoreItem *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreBaseFieldMFields \ingroup GrpLibOSGVCoreBase */
struct MFWeakVCoreItemPtr :
    public PointerMField<VCoreItem *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVCoreBaseFieldMFields \ingroup GrpLibOSGVCoreBase */
struct MFUncountedVCoreItemPtr :
    public PointerMField<VCoreItem *,
                         NoRefCountPolicy        > {};



/*! \ingroup GrpVCoreBaseFieldSFields \ingroup GrpLibOSGVCoreBase */
struct SFUnrecChildVCoreItemPtr :
    public ChildPointerSField<
        VCoreItem *, 
        UnrecordedRefCountPolicy,
        nsOSG + 1             > {};


/*! \ingroup GrpVCoreBaseFieldMFields \ingroup GrpLibOSGVCoreBase */
struct MFUnrecChildVCoreItemPtr :
    public ChildPointerMField<
        VCoreItem *, 
        UnrecordedRefCountPolicy,
        nsOSG + 1             > {};


#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGVCOREITEMFIELDS_H_ */
