/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGVCOREOSGSCENEITEMFIELDS_H_
#define _OSGVCOREOSGSCENEITEMFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGVCoreSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class VCoreOSGSceneItem;

OSG_GEN_CONTAINERPTR(VCoreOSGSceneItem);

/*! \ingroup GrpVCoreSystemFieldTraits
    \ingroup GrpLibOSGVCoreSystem
 */
template <>
struct FieldTraits<VCoreOSGSceneItem *> :
    public FieldTraitsFCPtrBase<VCoreOSGSceneItem *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<VCoreOSGSceneItem *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCORESYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFVCoreOSGSceneItemPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFVCoreOSGSceneItemPtr"; }
};

template<> inline
const Char8 *FieldTraits<VCoreOSGSceneItem *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecVCoreOSGSceneItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreOSGSceneItem *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecVCoreOSGSceneItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreOSGSceneItem *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakVCoreOSGSceneItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreOSGSceneItem *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdVCoreOSGSceneItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreOSGSceneItem *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecVCoreOSGSceneItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreOSGSceneItem *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecVCoreOSGSceneItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreOSGSceneItem *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakVCoreOSGSceneItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreOSGSceneItem *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdVCoreOSGSceneItemPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreOSGSceneItem *,
                      RecordedRefCountPolicy  > SFRecVCoreOSGSceneItemPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreOSGSceneItem *,
                      UnrecordedRefCountPolicy> SFUnrecVCoreOSGSceneItemPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreOSGSceneItem *,
                      WeakRefCountPolicy      > SFWeakVCoreOSGSceneItemPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreOSGSceneItem *,
                      NoRefCountPolicy        > SFUncountedVCoreOSGSceneItemPtr;


/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreOSGSceneItem *,
                      RecordedRefCountPolicy  > MFRecVCoreOSGSceneItemPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreOSGSceneItem *,
                      UnrecordedRefCountPolicy> MFUnrecVCoreOSGSceneItemPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreOSGSceneItem *,
                      WeakRefCountPolicy      > MFWeakVCoreOSGSceneItemPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreOSGSceneItem *,
                      NoRefCountPolicy        > MFUncountedVCoreOSGSceneItemPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFRecVCoreOSGSceneItemPtr : 
    public PointerSField<VCoreOSGSceneItem *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFUnrecVCoreOSGSceneItemPtr : 
    public PointerSField<VCoreOSGSceneItem *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFWeakVCoreOSGSceneItemPtr :
    public PointerSField<VCoreOSGSceneItem *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFUncountedVCoreOSGSceneItemPtr :
    public PointerSField<VCoreOSGSceneItem *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFRecVCoreOSGSceneItemPtr :
    public PointerMField<VCoreOSGSceneItem *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFUnrecVCoreOSGSceneItemPtr :
    public PointerMField<VCoreOSGSceneItem *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFWeakVCoreOSGSceneItemPtr :
    public PointerMField<VCoreOSGSceneItem *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFUncountedVCoreOSGSceneItemPtr :
    public PointerMField<VCoreOSGSceneItem *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGVCOREOSGSCENEITEMFIELDS_H_ */
