/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGVCOREARENAFIELDS_H_
#define _OSGVCOREARENAFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGVCoreSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class VCoreArena;

OSG_GEN_CONTAINERPTR(VCoreArena);

/*! \ingroup GrpVCoreSystemFieldTraits
    \ingroup GrpLibOSGVCoreSystem
 */
template <>
struct FieldTraits<VCoreArena *> :
    public FieldTraitsFCPtrBase<VCoreArena *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<VCoreArena *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCORESYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFVCoreArenaPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFVCoreArenaPtr"; }
};

template<> inline
const Char8 *FieldTraits<VCoreArena *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecVCoreArenaPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreArena *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecVCoreArenaPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreArena *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakVCoreArenaPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreArena *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdVCoreArenaPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreArena *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecVCoreArenaPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreArena *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecVCoreArenaPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreArena *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakVCoreArenaPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreArena *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdVCoreArenaPtr"; 
}


/*! \ingroup GrpVCoreSystemFieldTraits
 */
template <>
struct FieldTraits<VCoreArena *, 1> : 
    public FieldTraitsFCPtrBase<VCoreArena *, 1>
{
  private:

    static  DataType                                _type;

  public:

    static const bool bIsPointerField = true;

    typedef FieldTraits<VCoreArena *, 1>        Self;


    enum             { Convertible = Self::NotConvertible };
    
    static OSG_VCORESYSTEM_DLLMAPPING
                 DataType &getType (void);

    static const Char8    *getSName(void) 
    {
        return "SFParentVCoreArenaPtr"; 
    }

    static const Char8    *getMName(void) 
    { 
        return "MFParentVCoreArenaPtr"; 
    }
};

#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreArena *,
                      RecordedRefCountPolicy  > SFRecVCoreArenaPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreArena *,
                      UnrecordedRefCountPolicy> SFUnrecVCoreArenaPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreArena *,
                      WeakRefCountPolicy      > SFWeakVCoreArenaPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreArena *,
                      NoRefCountPolicy        > SFUncountedVCoreArenaPtr;


/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreArena *,
                      RecordedRefCountPolicy  > MFRecVCoreArenaPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreArena *,
                      UnrecordedRefCountPolicy> MFUnrecVCoreArenaPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreArena *,
                      WeakRefCountPolicy      > MFWeakVCoreArenaPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreArena *,
                      NoRefCountPolicy        > MFUncountedVCoreArenaPtr;



/*! \ingroup GrpVCoreSystemFieldSFields */
typedef ParentPointerSField<
          VCoreArena *, 
          NoRefCountPolicy,
          1    > SFParentVCoreArenaPtr;


#else // these are the doxygen hacks

/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFRecVCoreArenaPtr : 
    public PointerSField<VCoreArena *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFUnrecVCoreArenaPtr : 
    public PointerSField<VCoreArena *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFWeakVCoreArenaPtr :
    public PointerSField<VCoreArena *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFUncountedVCoreArenaPtr :
    public PointerSField<VCoreArena *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFRecVCoreArenaPtr :
    public PointerMField<VCoreArena *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFUnrecVCoreArenaPtr :
    public PointerMField<VCoreArena *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFWeakVCoreArenaPtr :
    public PointerMField<VCoreArena *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFUncountedVCoreArenaPtr :
    public PointerMField<VCoreArena *,
                         NoRefCountPolicy        > {};



/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFParentVCoreArenaPtr :
    public ParentPointerSField<
        VCoreArena *, 
        NoRefCountPolicy,
        1    > {};

#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGVCOREARENAFIELDS_H_ */
