/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGVIEWAREAFIELDS_H_
#define _OSGVIEWAREAFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGVCoRESystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

class Viewarea;

OSG_GEN_CONTAINERPTR(Viewarea);

VCORE_END_NAMESPACE

OSG_BEGIN_NAMESPACE

VCORE_IMPORT_NAMESPACE;
/*! \ingroup GrpVCoreSystemFieldTraits
    \ingroup GrpLibOSGVCoRESystem
 */
template <>
struct FieldTraits<Viewarea *, nsVCoRE> :
    public FieldTraitsFCPtrBase<Viewarea *, nsVCoRE>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<Viewarea *, nsVCoRE>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCORESYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<Viewarea *, nsVCoRE>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecViewareaPtr"; 
}

template<> inline
const Char8 *FieldTraits<Viewarea *, nsVCoRE>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecViewareaPtr"; 
}

template<> inline
const Char8 *FieldTraits<Viewarea *, nsVCoRE>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakViewareaPtr"; 
}

template<> inline
const Char8 *FieldTraits<Viewarea *, nsVCoRE>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdViewareaPtr"; 
}

template<> inline
const Char8 *FieldTraits<Viewarea *, nsVCoRE>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecViewareaPtr"; 
}

template<> inline
const Char8 *FieldTraits<Viewarea *, nsVCoRE>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecViewareaPtr"; 
}

template<> inline
const Char8 *FieldTraits<Viewarea *, nsVCoRE>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakViewareaPtr"; 
}

template<> inline
const Char8 *FieldTraits<Viewarea *, nsVCoRE>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdViewareaPtr"; 
}


OSG_END_NAMESPACE

VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<Viewarea *,
                      RecordedRefCountPolicy, nsVCoRE  > SFRecViewareaPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<Viewarea *,
                      UnrecordedRefCountPolicy, nsVCoRE> SFUnrecViewareaPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<Viewarea *,
                      WeakRefCountPolicy, nsVCoRE      > SFWeakViewareaPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<Viewarea *,
                      NoRefCountPolicy, nsVCoRE        > SFUncountedViewareaPtr;


/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<Viewarea *,
                      RecordedRefCountPolicy, nsVCoRE  > MFRecViewareaPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<Viewarea *,
                      UnrecordedRefCountPolicy, nsVCoRE> MFUnrecViewareaPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<Viewarea *,
                      WeakRefCountPolicy, nsVCoRE      > MFWeakViewareaPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<Viewarea *,
                      NoRefCountPolicy, nsVCoRE        > MFUncountedViewareaPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoRESystem */
struct SFRecViewareaPtr : 
    public PointerSField<Viewarea *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoRESystem */
struct SFUnrecViewareaPtr : 
    public PointerSField<Viewarea *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoRESystem */
struct SFWeakViewareaPtr :
    public PointerSField<Viewarea *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoRESystem */
struct SFUncountedViewareaPtr :
    public PointerSField<Viewarea *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoRESystem */
struct MFRecViewareaPtr :
    public PointerMField<Viewarea *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoRESystem */
struct MFUnrecViewareaPtr :
    public PointerMField<Viewarea *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoRESystem */
struct MFWeakViewareaPtr :
    public PointerMField<Viewarea *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoRESystem */
struct MFUncountedViewareaPtr :
    public PointerMField<Viewarea *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

VCORE_END_NAMESPACE

#endif /* _OSGVIEWAREAFIELDS_H_ */
