/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGVCVIEWAREAFIELDS_H_
#define _OSGVCVIEWAREAFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGVCoRESystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

class VCViewarea;

OSG_GEN_CONTAINERPTR(VCViewarea);

VCORE_END_NAMESPACE

OSG_BEGIN_NAMESPACE

VCORE_IMPORT_NAMESPACE;
/*! \ingroup GrpVCoreSystemFieldTraits
    \ingroup GrpLibOSGVCoRESystem
 */
template <>
struct FieldTraits<VCViewarea *, nsVCoRE> :
    public FieldTraitsFCPtrBase<VCViewarea *, nsVCoRE>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<VCViewarea *, nsVCoRE>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCORESYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<VCViewarea *, nsVCoRE>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecVCViewareaPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCViewarea *, nsVCoRE>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecVCViewareaPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCViewarea *, nsVCoRE>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakVCViewareaPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCViewarea *, nsVCoRE>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdVCViewareaPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCViewarea *, nsVCoRE>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecVCViewareaPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCViewarea *, nsVCoRE>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecVCViewareaPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCViewarea *, nsVCoRE>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakVCViewareaPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCViewarea *, nsVCoRE>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdVCViewareaPtr"; 
}


OSG_END_NAMESPACE

VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCViewarea *,
                      RecordedRefCountPolicy, nsVCoRE  > SFRecVCViewareaPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCViewarea *,
                      UnrecordedRefCountPolicy, nsVCoRE> SFUnrecVCViewareaPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCViewarea *,
                      WeakRefCountPolicy, nsVCoRE      > SFWeakVCViewareaPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCViewarea *,
                      NoRefCountPolicy, nsVCoRE        > SFUncountedVCViewareaPtr;


/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCViewarea *,
                      RecordedRefCountPolicy, nsVCoRE  > MFRecVCViewareaPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCViewarea *,
                      UnrecordedRefCountPolicy, nsVCoRE> MFUnrecVCViewareaPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCViewarea *,
                      WeakRefCountPolicy, nsVCoRE      > MFWeakVCViewareaPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCViewarea *,
                      NoRefCountPolicy, nsVCoRE        > MFUncountedVCViewareaPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoRESystem */
struct SFRecVCViewareaPtr : 
    public PointerSField<VCViewarea *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoRESystem */
struct SFUnrecVCViewareaPtr : 
    public PointerSField<VCViewarea *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoRESystem */
struct SFWeakVCViewareaPtr :
    public PointerSField<VCViewarea *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoRESystem */
struct SFUncountedVCViewareaPtr :
    public PointerSField<VCViewarea *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoRESystem */
struct MFRecVCViewareaPtr :
    public PointerMField<VCViewarea *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoRESystem */
struct MFUnrecVCViewareaPtr :
    public PointerMField<VCViewarea *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoRESystem */
struct MFWeakVCViewareaPtr :
    public PointerMField<VCViewarea *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoRESystem */
struct MFUncountedVCViewareaPtr :
    public PointerMField<VCViewarea *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

VCORE_END_NAMESPACE

#endif /* _OSGVCVIEWAREAFIELDS_H_ */
