/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGVCORERENDERERITEMFIELDS_H_
#define _OSGVCORERENDERERITEMFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGVCoreSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class VCoreRendererItem;

OSG_GEN_CONTAINERPTR(VCoreRendererItem);

/*! \ingroup GrpVCoreSystemFieldTraits
    \ingroup GrpLibOSGVCoreSystem
 */
template <>
struct FieldTraits<VCoreRendererItem *> :
    public FieldTraitsFCPtrBase<VCoreRendererItem *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<VCoreRendererItem *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCORESYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFVCoreRendererItemPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFVCoreRendererItemPtr"; }
};

template<> inline
const Char8 *FieldTraits<VCoreRendererItem *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecVCoreRendererItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreRendererItem *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecVCoreRendererItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreRendererItem *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakVCoreRendererItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreRendererItem *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdVCoreRendererItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreRendererItem *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecVCoreRendererItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreRendererItem *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecVCoreRendererItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreRendererItem *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakVCoreRendererItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreRendererItem *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdVCoreRendererItemPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreRendererItem *,
                      RecordedRefCountPolicy  > SFRecVCoreRendererItemPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreRendererItem *,
                      UnrecordedRefCountPolicy> SFUnrecVCoreRendererItemPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreRendererItem *,
                      WeakRefCountPolicy      > SFWeakVCoreRendererItemPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreRendererItem *,
                      NoRefCountPolicy        > SFUncountedVCoreRendererItemPtr;


/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreRendererItem *,
                      RecordedRefCountPolicy  > MFRecVCoreRendererItemPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreRendererItem *,
                      UnrecordedRefCountPolicy> MFUnrecVCoreRendererItemPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreRendererItem *,
                      WeakRefCountPolicy      > MFWeakVCoreRendererItemPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreRendererItem *,
                      NoRefCountPolicy        > MFUncountedVCoreRendererItemPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFRecVCoreRendererItemPtr : 
    public PointerSField<VCoreRendererItem *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFUnrecVCoreRendererItemPtr : 
    public PointerSField<VCoreRendererItem *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFWeakVCoreRendererItemPtr :
    public PointerSField<VCoreRendererItem *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFUncountedVCoreRendererItemPtr :
    public PointerSField<VCoreRendererItem *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFRecVCoreRendererItemPtr :
    public PointerMField<VCoreRendererItem *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFUnrecVCoreRendererItemPtr :
    public PointerMField<VCoreRendererItem *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFWeakVCoreRendererItemPtr :
    public PointerMField<VCoreRendererItem *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFUncountedVCoreRendererItemPtr :
    public PointerMField<VCoreRendererItem *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGVCORERENDERERITEMFIELDS_H_ */
