/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class VCoreViewarea
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGVCOREVIEWAREABASE_H_
#define _OSGVCOREVIEWAREABASE_H_
#ifdef __sgi
#pragma once
#endif


#include "OSGConfig.h"
#include "OSGVCoreSystemDef.h"

//#include "OSGBaseTypes.h"

#include "OSGAttachmentContainer.h" // Parent

#include "OSGBaseFields.h"              // RendererRef type
#include "OSGNodeFields.h"              // Root type
#include "OSGVCoreRendererItemFields.h" // Renderer type

#include "OSGVCoreViewareaFields.h"

OSG_BEGIN_NAMESPACE

class VCoreViewarea;

//! \brief VCoreViewarea Base Class.

class OSG_VCORESYSTEM_DLLMAPPING VCoreViewareaBase : public AttachmentContainer
{
  public:

    typedef AttachmentContainer Inherited;
    typedef AttachmentContainer ParentContainer;

    typedef Inherited::TypeObject TypeObject;
    typedef TypeObject::InitPhase InitPhase;

    OSG_GEN_INTERNALPTR(VCoreViewarea);

    /*==========================  PUBLIC  =================================*/

  public:

    enum
    {
        RendererRefFieldId = Inherited::NextFieldId,
        RootRefFieldId = RendererRefFieldId + 1,
        CameraRefFieldId = RootRefFieldId + 1,
        RootFieldId = CameraRefFieldId + 1,
        RendererFieldId = RootFieldId + 1,
        NextFieldId = RendererFieldId + 1
    };

    static const OSG::BitVector RendererRefFieldMask =
        (TypeTraits<BitVector>::One << RendererRefFieldId);
    static const OSG::BitVector RootRefFieldMask =
        (TypeTraits<BitVector>::One << RootRefFieldId);
    static const OSG::BitVector CameraRefFieldMask =
        (TypeTraits<BitVector>::One << CameraRefFieldId);
    static const OSG::BitVector RootFieldMask =
        (TypeTraits<BitVector>::One << RootFieldId);
    static const OSG::BitVector RendererFieldMask =
        (TypeTraits<BitVector>::One << RendererFieldId);
    static const OSG::BitVector NextFieldMask =
        (TypeTraits<BitVector>::One << NextFieldId);
        
    typedef SFString          SFRendererRefType;
    typedef SFString          SFRootRefType;
    typedef SFString          SFCameraRefType;
    typedef SFUnrecNodePtr    SFRootType;
    typedef SFUnrecVCoreRendererItemPtr SFRendererType;

    /*---------------------------------------------------------------------*/
    /*! \name                    Class Get                                 */
    /*! \{                                                                 */

    static FieldContainerType &getClassType   (void);
    static UInt32              getClassTypeId (void);
    static UInt16              getClassGroupId(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                FieldContainer Get                            */
    /*! \{                                                                 */

    virtual       FieldContainerType &getType         (void);
    virtual const FieldContainerType &getType         (void) const;

    virtual       UInt32              getContainerSize(void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Get                                 */
    /*! \{                                                                 */


                  SFString            *editSFRendererRef    (void);
            const SFString            *getSFRendererRef     (void) const;

                  SFString            *editSFRootRef        (void);
            const SFString            *getSFRootRef         (void) const;

                  SFString            *editSFCameraRef      (void);
            const SFString            *getSFCameraRef       (void) const;
            const SFUnrecNodePtr      *getSFRoot           (void) const;
                  SFUnrecNodePtr      *editSFRoot           (void);
            const SFUnrecVCoreRendererItemPtr *getSFRenderer       (void) const;
                  SFUnrecVCoreRendererItemPtr *editSFRenderer       (void);


                  std::string         &editRendererRef    (void);
            const std::string         &getRendererRef     (void) const;

                  std::string         &editRootRef        (void);
            const std::string         &getRootRef         (void) const;

                  std::string         &editCameraRef      (void);
            const std::string         &getCameraRef       (void) const;

                  Node * getRoot           (void) const;

                  VCoreRendererItem * getRenderer       (void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Set                                 */
    /*! \{                                                                 */

            void setRendererRef    (const std::string &value);
            void setRootRef        (const std::string &value);
            void setCameraRef      (const std::string &value);
            void setRoot           (Node * const value);
            void setRenderer       (VCoreRendererItem * const value);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                Ptr Field Set                                 */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                Ptr MField Set                                */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Binary Access                              */
    /*! \{                                                                 */

    virtual UInt32 getBinSize (ConstFieldMaskArg  whichField);
    virtual void   copyToBin  (BinaryDataHandler &pMem,
                               ConstFieldMaskArg  whichField);
    virtual void   copyFromBin(BinaryDataHandler &pMem,
                               ConstFieldMaskArg  whichField);


    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Construction                               */
    /*! \{                                                                 */

    static  VCoreViewareaTransitPtr  create          (void);
    static  VCoreViewarea           *createEmpty     (void);

    static  VCoreViewareaTransitPtr  createLocal     (
                                               BitVector bFlags = FCLocal::All);

    static  VCoreViewarea            *createEmptyLocal(
                                              BitVector bFlags = FCLocal::All);

    static  VCoreViewareaTransitPtr  createDependent  (BitVector bFlags);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Copy                                   */
    /*! \{                                                                 */

    virtual FieldContainerTransitPtr shallowCopy     (void) const;
    virtual FieldContainerTransitPtr shallowCopyLocal(
                                       BitVector bFlags = FCLocal::All) const;
    virtual FieldContainerTransitPtr shallowCopyDependent(
                                                      BitVector bFlags) const;

    /*! \}                                                                 */
    /*=========================  PROTECTED  ===============================*/

  protected:

    static TypeObject _type;

    static       void   classDescInserter(TypeObject &oType);
    static const Char8 *getClassname     (void             );

    /*---------------------------------------------------------------------*/
    /*! \name                      Fields                                  */
    /*! \{                                                                 */

    SFString          _sfRendererRef;
    SFString          _sfRootRef;
    SFString          _sfCameraRef;
    SFUnrecNodePtr    _sfRoot;
    SFUnrecVCoreRendererItemPtr _sfRenderer;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Constructors                               */
    /*! \{                                                                 */

    VCoreViewareaBase(void);
    VCoreViewareaBase(const VCoreViewareaBase &source);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Destructors                                */
    /*! \{                                                                 */

    virtual ~VCoreViewareaBase(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                     onCreate                                */
    /*! \{                                                                 */

    void onCreate(const VCoreViewarea *source = NULL);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Generic Field Access                      */
    /*! \{                                                                 */

    GetFieldHandlePtr  getHandleRendererRef     (void) const;
    EditFieldHandlePtr editHandleRendererRef    (void);
    GetFieldHandlePtr  getHandleRootRef         (void) const;
    EditFieldHandlePtr editHandleRootRef        (void);
    GetFieldHandlePtr  getHandleCameraRef       (void) const;
    EditFieldHandlePtr editHandleCameraRef      (void);
    GetFieldHandlePtr  getHandleRoot            (void) const;
    EditFieldHandlePtr editHandleRoot           (void);
    GetFieldHandlePtr  getHandleRenderer        (void) const;
    EditFieldHandlePtr editHandleRenderer       (void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

#ifdef OSG_MT_CPTR_ASPECT
    virtual void execSyncV(      FieldContainer    &oFrom,
                                 ConstFieldMaskArg  whichField,
                                 AspectOffsetStore &oOffsets,
                                 ConstFieldMaskArg  syncMode  ,
                           const UInt32             uiSyncInfo);

            void execSync (      VCoreViewareaBase *pFrom,
                                 ConstFieldMaskArg  whichField,
                                 AspectOffsetStore &oOffsets,
                                 ConstFieldMaskArg  syncMode  ,
                           const UInt32             uiSyncInfo);
#endif

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Edit                                   */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                     Aspect Create                            */
    /*! \{                                                                 */

#ifdef OSG_MT_CPTR_ASPECT
    virtual FieldContainer *createAspectCopy(
                                    const FieldContainer *pRefAspect) const;
#endif

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Edit                                   */
    /*! \{                                                                 */
    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

    virtual void resolveLinks(void);

    /*! \}                                                                 */
    /*==========================  PRIVATE  ================================*/

  private:
    /*---------------------------------------------------------------------*/

    // prohibit default functions (move to 'public' if you need one)
    void operator =(const VCoreViewareaBase &source);
};

typedef VCoreViewareaBase *VCoreViewareaBaseP;

OSG_END_NAMESPACE

#endif /* _OSGVCOREVIEWAREABASE_H_ */
