/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class Viewarea!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"



#include "OSGNode.h"                    // Root Class
#include "OSGVCoRERendererItem.h"       // Renderer Class

#include "OSGVCoREViewareaBase.h"
#include "OSGVCoREViewarea.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

VCORE_IMPORT_NAMESPACE;

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::Viewarea
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var std::string     ViewareaBase::_sfRendererRef
    
*/

/*! \var std::string     ViewareaBase::_sfRootRef
    
*/

/*! \var std::string     ViewareaBase::_sfCameraRef
    
*/

/*! \var Node *          ViewareaBase::_sfRoot
    
*/

/*! \var RendererItem *  ViewareaBase::_sfRenderer
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<Viewarea *, nsVCoRE>::_type("ViewareaPtr", "AttachmentContainerPtr", nsVCoRE);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(Viewarea *, nsVCoRE)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           Viewarea *,
                           nsVCoRE);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           Viewarea *,
                           nsVCoRE);

OSG_END_NAMESPACE

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

void ViewareaBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFString::Description(
        SFString::getClassType(),
        "rendererRef",
        "",
        RendererRefFieldId, RendererRefFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&Viewarea::editHandleRendererRef),
        static_cast<FieldGetMethodSig >(&Viewarea::getHandleRendererRef));

    oType.addInitialDesc(pDesc);

    pDesc = new SFString::Description(
        SFString::getClassType(),
        "rootRef",
        "",
        RootRefFieldId, RootRefFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&Viewarea::editHandleRootRef),
        static_cast<FieldGetMethodSig >(&Viewarea::getHandleRootRef));

    oType.addInitialDesc(pDesc);

    pDesc = new SFString::Description(
        SFString::getClassType(),
        "cameraRef",
        "",
        CameraRefFieldId, CameraRefFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&Viewarea::editHandleCameraRef),
        static_cast<FieldGetMethodSig >(&Viewarea::getHandleCameraRef));

    oType.addInitialDesc(pDesc);

    pDesc = new SFUnrecNodePtr::Description(
        SFUnrecNodePtr::getClassType(),
        "root",
        "",
        RootFieldId, RootFieldMask,
        true,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&Viewarea::editHandleRoot),
        static_cast<FieldGetMethodSig >(&Viewarea::getHandleRoot));

    oType.addInitialDesc(pDesc);

    pDesc = new SFUnrecRendererItemPtr::Description(
        SFUnrecRendererItemPtr::getClassType(),
        "renderer",
        "",
        RendererFieldId, RendererFieldMask,
        true,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&Viewarea::editHandleRenderer),
        static_cast<FieldGetMethodSig >(&Viewarea::getHandleRenderer));

    oType.addInitialDesc(pDesc);
}


ViewareaBase::TypeObject ViewareaBase::_type(
    ViewareaBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsVCoRE, //Namespace
    reinterpret_cast<PrototypeCreateF>(&ViewareaBase::createEmptyLocal),
    Viewarea::initMethod,
    Viewarea::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&Viewarea::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\" ?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"Viewarea\"\n"
    "    parent=\"AttachmentContainer\"\n"
    "    library=\"VCoRESystem\"\n"
    "    structure=\"concrete\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    isNodeCore=\"false\"\n"
    "    isBundle=\"true\"\n"
    "    docGroupBase=\"GrpVCoreSystem\"\n"
    "    libnamespace=\"VCoRE\"\n"
    "   >\n"
    "  <Field\n"
    "      name=\"rendererRef\"\n"
    "      type=\"std::string\"\n"
    "      cardinality=\"single\"\n"
    "      visibility=\"external\"\n"
    "      access=\"public\"\n"
    "      >\n"
    "  </Field>\n"
    "  <Field\n"
    "      name=\"rootRef\"\n"
    "      type=\"std::string\"\n"
    "      cardinality=\"single\"\n"
    "      visibility=\"external\"\n"
    "      access=\"public\"\n"
    "      >\n"
    "  </Field>\n"
    "  <Field\n"
    "      name=\"cameraRef\"\n"
    "      type=\"std::string\"\n"
    "      cardinality=\"single\"\n"
    "      visibility=\"external\"\n"
    "      access=\"public\"\n"
    "      >\n"
    "  </Field>\n"
    "  <Field\n"
    "\t name=\"root\"\n"
    "\t type=\"Node\"\n"
    "\t cardinality=\"single\"\n"
    "\t visibility=\"internal\"\n"
    "\t defaultValue=\"NULL\"\n"
    "\t access=\"public\"\n"
    "     category=\"pointer\"\n"
    "\t >\n"
    "  </Field>\n"
    "  <Field\n"
    "\t name=\"renderer\"\n"
    "\t type=\"VCoRE::RendererItem\"\n"
    "\t cardinality=\"single\"\n"
    "\t visibility=\"internal\"\n"
    "\t defaultValue=\"NULL\"\n"
    "\t access=\"public\"\n"
    "     category=\"pointer\"\n"
    "\t >\n"
    "  </Field>\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &ViewareaBase::getType(void)
{
    return _type;
}

const FieldContainerType &ViewareaBase::getType(void) const
{
    return _type;
}

UInt32 ViewareaBase::getContainerSize(void) const
{
    return sizeof(Viewarea);
}

/*------------------------- decorator get ------------------------------*/


SFString *ViewareaBase::editSFRendererRef(void)
{
    editSField(RendererRefFieldMask);

    return &_sfRendererRef;
}

const SFString *ViewareaBase::getSFRendererRef(void) const
{
    return &_sfRendererRef;
}


SFString *ViewareaBase::editSFRootRef(void)
{
    editSField(RootRefFieldMask);

    return &_sfRootRef;
}

const SFString *ViewareaBase::getSFRootRef(void) const
{
    return &_sfRootRef;
}


SFString *ViewareaBase::editSFCameraRef(void)
{
    editSField(CameraRefFieldMask);

    return &_sfCameraRef;
}

const SFString *ViewareaBase::getSFCameraRef(void) const
{
    return &_sfCameraRef;
}


//! Get the Viewarea::_sfRoot field.
const SFUnrecNodePtr *ViewareaBase::getSFRoot(void) const
{
    return &_sfRoot;
}

SFUnrecNodePtr      *ViewareaBase::editSFRoot           (void)
{
    editSField(RootFieldMask);

    return &_sfRoot;
}

//! Get the Viewarea::_sfRenderer field.
const SFUnrecRendererItemPtr *ViewareaBase::getSFRenderer(void) const
{
    return &_sfRenderer;
}

SFUnrecRendererItemPtr *ViewareaBase::editSFRenderer       (void)
{
    editSField(RendererFieldMask);

    return &_sfRenderer;
}





/*------------------------------ access -----------------------------------*/

UInt32 ViewareaBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (RendererRefFieldMask & whichField))
    {
        returnValue += _sfRendererRef.getBinSize();
    }
    if(FieldBits::NoField != (RootRefFieldMask & whichField))
    {
        returnValue += _sfRootRef.getBinSize();
    }
    if(FieldBits::NoField != (CameraRefFieldMask & whichField))
    {
        returnValue += _sfCameraRef.getBinSize();
    }
    if(FieldBits::NoField != (RootFieldMask & whichField))
    {
        returnValue += _sfRoot.getBinSize();
    }
    if(FieldBits::NoField != (RendererFieldMask & whichField))
    {
        returnValue += _sfRenderer.getBinSize();
    }

    return returnValue;
}

void ViewareaBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (RendererRefFieldMask & whichField))
    {
        _sfRendererRef.copyToBin(pMem);
    }
    if(FieldBits::NoField != (RootRefFieldMask & whichField))
    {
        _sfRootRef.copyToBin(pMem);
    }
    if(FieldBits::NoField != (CameraRefFieldMask & whichField))
    {
        _sfCameraRef.copyToBin(pMem);
    }
    if(FieldBits::NoField != (RootFieldMask & whichField))
    {
        _sfRoot.copyToBin(pMem);
    }
    if(FieldBits::NoField != (RendererFieldMask & whichField))
    {
        _sfRenderer.copyToBin(pMem);
    }
}

void ViewareaBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (RendererRefFieldMask & whichField))
    {
        editSField(RendererRefFieldMask);
        _sfRendererRef.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (RootRefFieldMask & whichField))
    {
        editSField(RootRefFieldMask);
        _sfRootRef.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (CameraRefFieldMask & whichField))
    {
        editSField(CameraRefFieldMask);
        _sfCameraRef.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (RootFieldMask & whichField))
    {
        editSField(RootFieldMask);
        _sfRoot.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (RendererFieldMask & whichField))
    {
        editSField(RendererFieldMask);
        _sfRenderer.copyFromBin(pMem);
    }
}

//! create a new instance of the class
ViewareaTransitPtr ViewareaBase::createLocal(BitVector bFlags)
{
    ViewareaTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<Viewarea>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
ViewareaTransitPtr ViewareaBase::createDependent(BitVector bFlags)
{
    ViewareaTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<Viewarea>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
ViewareaTransitPtr ViewareaBase::create(void)
{
    return createLocal();
}

Viewarea *ViewareaBase::createEmptyLocal(BitVector bFlags)
{
    Viewarea *returnValue;

    newPtr<Viewarea>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
Viewarea *ViewareaBase::createEmpty(void)
{
    return createEmptyLocal();
}


FieldContainerTransitPtr ViewareaBase::shallowCopyLocal(
    BitVector bFlags) const
{
    Viewarea *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const Viewarea *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr ViewareaBase::shallowCopyDependent(
    BitVector bFlags) const
{
    Viewarea *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const Viewarea *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr ViewareaBase::shallowCopy(void) const
{
    return shallowCopyLocal();
}




/*------------------------- constructors ----------------------------------*/

ViewareaBase::ViewareaBase(void) :
    Inherited(),
    _sfRendererRef            (),
    _sfRootRef                (),
    _sfCameraRef              (),
    _sfRoot                   (NULL),
    _sfRenderer               (NULL)
{
}

ViewareaBase::ViewareaBase(const ViewareaBase &source) :
    Inherited(source),
    _sfRendererRef            (source._sfRendererRef            ),
    _sfRootRef                (source._sfRootRef                ),
    _sfCameraRef              (source._sfCameraRef              ),
    _sfRoot                   (NULL),
    _sfRenderer               (NULL)
{
}


/*-------------------------- destructors ----------------------------------*/

ViewareaBase::~ViewareaBase(void)
{
}

void ViewareaBase::onCreate(const Viewarea *source)
{
    Inherited::onCreate(source);

    if(source != NULL)
    {
        Viewarea *pThis = static_cast<Viewarea *>(this);

        pThis->setRoot(source->getRoot());

        pThis->setRenderer(source->getRenderer());
    }
}

GetFieldHandlePtr ViewareaBase::getHandleRendererRef     (void) const
{
    SFString::GetHandlePtr returnValue(
        new  SFString::GetHandle(
             &_sfRendererRef,
             this->getType().getFieldDesc(RendererRefFieldId),
             const_cast<ViewareaBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr ViewareaBase::editHandleRendererRef    (void)
{
    SFString::EditHandlePtr returnValue(
        new  SFString::EditHandle(
             &_sfRendererRef,
             this->getType().getFieldDesc(RendererRefFieldId),
             this));


    editSField(RendererRefFieldMask);

    return returnValue;
}

GetFieldHandlePtr ViewareaBase::getHandleRootRef         (void) const
{
    SFString::GetHandlePtr returnValue(
        new  SFString::GetHandle(
             &_sfRootRef,
             this->getType().getFieldDesc(RootRefFieldId),
             const_cast<ViewareaBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr ViewareaBase::editHandleRootRef        (void)
{
    SFString::EditHandlePtr returnValue(
        new  SFString::EditHandle(
             &_sfRootRef,
             this->getType().getFieldDesc(RootRefFieldId),
             this));


    editSField(RootRefFieldMask);

    return returnValue;
}

GetFieldHandlePtr ViewareaBase::getHandleCameraRef       (void) const
{
    SFString::GetHandlePtr returnValue(
        new  SFString::GetHandle(
             &_sfCameraRef,
             this->getType().getFieldDesc(CameraRefFieldId),
             const_cast<ViewareaBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr ViewareaBase::editHandleCameraRef      (void)
{
    SFString::EditHandlePtr returnValue(
        new  SFString::EditHandle(
             &_sfCameraRef,
             this->getType().getFieldDesc(CameraRefFieldId),
             this));


    editSField(CameraRefFieldMask);

    return returnValue;
}

GetFieldHandlePtr ViewareaBase::getHandleRoot            (void) const
{
    SFUnrecNodePtr::GetHandlePtr returnValue(
        new  SFUnrecNodePtr::GetHandle(
             &_sfRoot,
             this->getType().getFieldDesc(RootFieldId),
             const_cast<ViewareaBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr ViewareaBase::editHandleRoot           (void)
{
    SFUnrecNodePtr::EditHandlePtr returnValue(
        new  SFUnrecNodePtr::EditHandle(
             &_sfRoot,
             this->getType().getFieldDesc(RootFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&Viewarea::setRoot,
                    static_cast<Viewarea *>(this), _1));

    editSField(RootFieldMask);

    return returnValue;
}

GetFieldHandlePtr ViewareaBase::getHandleRenderer        (void) const
{
    SFUnrecRendererItemPtr::GetHandlePtr returnValue(
        new  SFUnrecRendererItemPtr::GetHandle(
             &_sfRenderer,
             this->getType().getFieldDesc(RendererFieldId),
             const_cast<ViewareaBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr ViewareaBase::editHandleRenderer       (void)
{
    SFUnrecRendererItemPtr::EditHandlePtr returnValue(
        new  SFUnrecRendererItemPtr::EditHandle(
             &_sfRenderer,
             this->getType().getFieldDesc(RendererFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&Viewarea::setRenderer,
                    static_cast<Viewarea *>(this), _1));

    editSField(RendererFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void ViewareaBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    Viewarea *pThis = static_cast<Viewarea *>(this);

    pThis->execSync(static_cast<Viewarea *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *ViewareaBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    Viewarea *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const Viewarea *>(pRefAspect),
                  dynamic_cast<const Viewarea *>(this));

    return returnValue;
}
#endif

void ViewareaBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<Viewarea *>(this)->setRoot(NULL);

    static_cast<Viewarea *>(this)->setRenderer(NULL);


}


VCORE_END_NAMESPACE
