/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGVCOREWINDOWFIELDS_H_
#define _OSGVCOREWINDOWFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGVCoreSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class VCoreWindow;

OSG_GEN_CONTAINERPTR(VCoreWindow);

/*! \ingroup GrpVCoreSystemFieldTraits
    \ingroup GrpLibOSGVCoreSystem
 */
template <>
struct FieldTraits<VCoreWindow *> :
    public FieldTraitsFCPtrBase<VCoreWindow *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<VCoreWindow *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCORESYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFVCoreWindowPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFVCoreWindowPtr"; }
};

template<> inline
const Char8 *FieldTraits<VCoreWindow *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecVCoreWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreWindow *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecVCoreWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreWindow *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakVCoreWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreWindow *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdVCoreWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreWindow *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecVCoreWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreWindow *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecVCoreWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreWindow *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakVCoreWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreWindow *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdVCoreWindowPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreWindow *,
                      RecordedRefCountPolicy  > SFRecVCoreWindowPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreWindow *,
                      UnrecordedRefCountPolicy> SFUnrecVCoreWindowPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreWindow *,
                      WeakRefCountPolicy      > SFWeakVCoreWindowPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreWindow *,
                      NoRefCountPolicy        > SFUncountedVCoreWindowPtr;


/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreWindow *,
                      RecordedRefCountPolicy  > MFRecVCoreWindowPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreWindow *,
                      UnrecordedRefCountPolicy> MFUnrecVCoreWindowPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreWindow *,
                      WeakRefCountPolicy      > MFWeakVCoreWindowPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreWindow *,
                      NoRefCountPolicy        > MFUncountedVCoreWindowPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFRecVCoreWindowPtr : 
    public PointerSField<VCoreWindow *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFUnrecVCoreWindowPtr : 
    public PointerSField<VCoreWindow *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFWeakVCoreWindowPtr :
    public PointerSField<VCoreWindow *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFUncountedVCoreWindowPtr :
    public PointerSField<VCoreWindow *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFRecVCoreWindowPtr :
    public PointerMField<VCoreWindow *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFUnrecVCoreWindowPtr :
    public PointerMField<VCoreWindow *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFWeakVCoreWindowPtr :
    public PointerMField<VCoreWindow *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFUncountedVCoreWindowPtr :
    public PointerMField<VCoreWindow *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGVCOREWINDOWFIELDS_H_ */
