/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGREPOSITORYFIELDS_H_
#define _OSGREPOSITORYFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGVCoRESystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

class Repository;

OSG_GEN_CONTAINERPTR(Repository);

VCORE_END_NAMESPACE

OSG_BEGIN_NAMESPACE

VCORE_IMPORT_NAMESPACE;
/*! \ingroup GrpVCoreSystemFieldTraits
    \ingroup GrpLibOSGVCoRESystem
 */
template <>
struct FieldTraits<Repository *, nsVCoRE> :
    public FieldTraitsFCPtrBase<Repository *, nsVCoRE>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<Repository *, nsVCoRE>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCORESYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<Repository *, nsVCoRE>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecRepositoryPtr"; 
}

template<> inline
const Char8 *FieldTraits<Repository *, nsVCoRE>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecRepositoryPtr"; 
}

template<> inline
const Char8 *FieldTraits<Repository *, nsVCoRE>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakRepositoryPtr"; 
}

template<> inline
const Char8 *FieldTraits<Repository *, nsVCoRE>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdRepositoryPtr"; 
}

template<> inline
const Char8 *FieldTraits<Repository *, nsVCoRE>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecRepositoryPtr"; 
}

template<> inline
const Char8 *FieldTraits<Repository *, nsVCoRE>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecRepositoryPtr"; 
}

template<> inline
const Char8 *FieldTraits<Repository *, nsVCoRE>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakRepositoryPtr"; 
}

template<> inline
const Char8 *FieldTraits<Repository *, nsVCoRE>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdRepositoryPtr"; 
}


OSG_END_NAMESPACE

VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<Repository *,
                      RecordedRefCountPolicy, nsVCoRE  > SFRecRepositoryPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<Repository *,
                      UnrecordedRefCountPolicy, nsVCoRE> SFUnrecRepositoryPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<Repository *,
                      WeakRefCountPolicy, nsVCoRE      > SFWeakRepositoryPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<Repository *,
                      NoRefCountPolicy, nsVCoRE        > SFUncountedRepositoryPtr;


/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<Repository *,
                      RecordedRefCountPolicy, nsVCoRE  > MFRecRepositoryPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<Repository *,
                      UnrecordedRefCountPolicy, nsVCoRE> MFUnrecRepositoryPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<Repository *,
                      WeakRefCountPolicy, nsVCoRE      > MFWeakRepositoryPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<Repository *,
                      NoRefCountPolicy, nsVCoRE        > MFUncountedRepositoryPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoRESystem */
struct SFRecRepositoryPtr : 
    public PointerSField<Repository *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoRESystem */
struct SFUnrecRepositoryPtr : 
    public PointerSField<Repository *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoRESystem */
struct SFWeakRepositoryPtr :
    public PointerSField<Repository *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoRESystem */
struct SFUncountedRepositoryPtr :
    public PointerSField<Repository *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoRESystem */
struct MFRecRepositoryPtr :
    public PointerMField<Repository *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoRESystem */
struct MFUnrecRepositoryPtr :
    public PointerMField<Repository *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoRESystem */
struct MFWeakRepositoryPtr :
    public PointerMField<Repository *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoRESystem */
struct MFUncountedRepositoryPtr :
    public PointerMField<Repository *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

VCORE_END_NAMESPACE

#endif /* _OSGREPOSITORYFIELDS_H_ */
