/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGOSGSCENEITEMFIELDS_H_
#define _OSGOSGSCENEITEMFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGVCoRESystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

class OSGSceneItem;

OSG_GEN_CONTAINERPTR(OSGSceneItem);

VCORE_END_NAMESPACE

OSG_BEGIN_NAMESPACE

VCORE_IMPORT_NAMESPACE;
/*! \ingroup GrpVCoreSystemFieldTraits
    \ingroup GrpLibOSGVCoRESystem
 */
template <>
struct FieldTraits<OSGSceneItem *, nsVCoRE> :
    public FieldTraitsFCPtrBase<OSGSceneItem *, nsVCoRE>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<OSGSceneItem *, nsVCoRE>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCORESYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<OSGSceneItem *, nsVCoRE>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecOSGSceneItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<OSGSceneItem *, nsVCoRE>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecOSGSceneItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<OSGSceneItem *, nsVCoRE>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakOSGSceneItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<OSGSceneItem *, nsVCoRE>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdOSGSceneItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<OSGSceneItem *, nsVCoRE>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecOSGSceneItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<OSGSceneItem *, nsVCoRE>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecOSGSceneItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<OSGSceneItem *, nsVCoRE>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakOSGSceneItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<OSGSceneItem *, nsVCoRE>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdOSGSceneItemPtr"; 
}


OSG_END_NAMESPACE

VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<OSGSceneItem *,
                      RecordedRefCountPolicy, nsVCoRE  > SFRecOSGSceneItemPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<OSGSceneItem *,
                      UnrecordedRefCountPolicy, nsVCoRE> SFUnrecOSGSceneItemPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<OSGSceneItem *,
                      WeakRefCountPolicy, nsVCoRE      > SFWeakOSGSceneItemPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<OSGSceneItem *,
                      NoRefCountPolicy, nsVCoRE        > SFUncountedOSGSceneItemPtr;


/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<OSGSceneItem *,
                      RecordedRefCountPolicy, nsVCoRE  > MFRecOSGSceneItemPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<OSGSceneItem *,
                      UnrecordedRefCountPolicy, nsVCoRE> MFUnrecOSGSceneItemPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<OSGSceneItem *,
                      WeakRefCountPolicy, nsVCoRE      > MFWeakOSGSceneItemPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<OSGSceneItem *,
                      NoRefCountPolicy, nsVCoRE        > MFUncountedOSGSceneItemPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoRESystem */
struct SFRecOSGSceneItemPtr : 
    public PointerSField<OSGSceneItem *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoRESystem */
struct SFUnrecOSGSceneItemPtr : 
    public PointerSField<OSGSceneItem *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoRESystem */
struct SFWeakOSGSceneItemPtr :
    public PointerSField<OSGSceneItem *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoRESystem */
struct SFUncountedOSGSceneItemPtr :
    public PointerSField<OSGSceneItem *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoRESystem */
struct MFRecOSGSceneItemPtr :
    public PointerMField<OSGSceneItem *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoRESystem */
struct MFUnrecOSGSceneItemPtr :
    public PointerMField<OSGSceneItem *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoRESystem */
struct MFWeakOSGSceneItemPtr :
    public PointerMField<OSGSceneItem *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoRESystem */
struct MFUncountedOSGSceneItemPtr :
    public PointerMField<OSGSceneItem *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

VCORE_END_NAMESPACE

#endif /* _OSGOSGSCENEITEMFIELDS_H_ */
