/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGRENDERERITEMFIELDS_H_
#define _OSGRENDERERITEMFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGVCoRESystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

class RendererItem;

OSG_GEN_CONTAINERPTR(RendererItem);

VCORE_END_NAMESPACE

OSG_BEGIN_NAMESPACE

VCORE_IMPORT_NAMESPACE;
/*! \ingroup GrpVCoreSystemFieldTraits
    \ingroup GrpLibOSGVCoRESystem
 */
template <>
struct FieldTraits<RendererItem *, nsVCoRE> :
    public FieldTraitsFCPtrBase<RendererItem *, nsVCoRE>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<RendererItem *, nsVCoRE>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCORESYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<RendererItem *, nsVCoRE>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecRendererItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<RendererItem *, nsVCoRE>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecRendererItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<RendererItem *, nsVCoRE>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakRendererItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<RendererItem *, nsVCoRE>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdRendererItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<RendererItem *, nsVCoRE>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecRendererItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<RendererItem *, nsVCoRE>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecRendererItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<RendererItem *, nsVCoRE>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakRendererItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<RendererItem *, nsVCoRE>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdRendererItemPtr"; 
}


OSG_END_NAMESPACE

VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<RendererItem *,
                      RecordedRefCountPolicy, nsVCoRE  > SFRecRendererItemPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<RendererItem *,
                      UnrecordedRefCountPolicy, nsVCoRE> SFUnrecRendererItemPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<RendererItem *,
                      WeakRefCountPolicy, nsVCoRE      > SFWeakRendererItemPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<RendererItem *,
                      NoRefCountPolicy, nsVCoRE        > SFUncountedRendererItemPtr;


/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<RendererItem *,
                      RecordedRefCountPolicy, nsVCoRE  > MFRecRendererItemPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<RendererItem *,
                      UnrecordedRefCountPolicy, nsVCoRE> MFUnrecRendererItemPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<RendererItem *,
                      WeakRefCountPolicy, nsVCoRE      > MFWeakRendererItemPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<RendererItem *,
                      NoRefCountPolicy, nsVCoRE        > MFUncountedRendererItemPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoRESystem */
struct SFRecRendererItemPtr : 
    public PointerSField<RendererItem *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoRESystem */
struct SFUnrecRendererItemPtr : 
    public PointerSField<RendererItem *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoRESystem */
struct SFWeakRendererItemPtr :
    public PointerSField<RendererItem *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoRESystem */
struct SFUncountedRendererItemPtr :
    public PointerSField<RendererItem *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoRESystem */
struct MFRecRendererItemPtr :
    public PointerMField<RendererItem *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoRESystem */
struct MFUnrecRendererItemPtr :
    public PointerMField<RendererItem *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoRESystem */
struct MFWeakRendererItemPtr :
    public PointerMField<RendererItem *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoRESystem */
struct MFUncountedRendererItemPtr :
    public PointerMField<RendererItem *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

VCORE_END_NAMESPACE

#endif /* _OSGRENDERERITEMFIELDS_H_ */
