/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGVCOREVIEWAREAFIELDS_H_
#define _OSGVCOREVIEWAREAFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGVCoreSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class VCoreViewarea;

OSG_GEN_CONTAINERPTR(VCoreViewarea);

/*! \ingroup GrpVCoreSystemFieldTraits
    \ingroup GrpLibOSGVCoreSystem
 */
template <>
struct FieldTraits<VCoreViewarea *> :
    public FieldTraitsFCPtrBase<VCoreViewarea *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<VCoreViewarea *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCORESYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFVCoreViewareaPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFVCoreViewareaPtr"; }
};

template<> inline
const Char8 *FieldTraits<VCoreViewarea *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecVCoreViewareaPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreViewarea *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecVCoreViewareaPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreViewarea *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakVCoreViewareaPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreViewarea *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdVCoreViewareaPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreViewarea *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecVCoreViewareaPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreViewarea *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecVCoreViewareaPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreViewarea *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakVCoreViewareaPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreViewarea *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdVCoreViewareaPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreViewarea *,
                      RecordedRefCountPolicy  > SFRecVCoreViewareaPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreViewarea *,
                      UnrecordedRefCountPolicy> SFUnrecVCoreViewareaPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreViewarea *,
                      WeakRefCountPolicy      > SFWeakVCoreViewareaPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreViewarea *,
                      NoRefCountPolicy        > SFUncountedVCoreViewareaPtr;


/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreViewarea *,
                      RecordedRefCountPolicy  > MFRecVCoreViewareaPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreViewarea *,
                      UnrecordedRefCountPolicy> MFUnrecVCoreViewareaPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreViewarea *,
                      WeakRefCountPolicy      > MFWeakVCoreViewareaPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreViewarea *,
                      NoRefCountPolicy        > MFUncountedVCoreViewareaPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFRecVCoreViewareaPtr : 
    public PointerSField<VCoreViewarea *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFUnrecVCoreViewareaPtr : 
    public PointerSField<VCoreViewarea *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFWeakVCoreViewareaPtr :
    public PointerSField<VCoreViewarea *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFUncountedVCoreViewareaPtr :
    public PointerSField<VCoreViewarea *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFRecVCoreViewareaPtr :
    public PointerMField<VCoreViewarea *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFUnrecVCoreViewareaPtr :
    public PointerMField<VCoreViewarea *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFWeakVCoreViewareaPtr :
    public PointerMField<VCoreViewarea *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFUncountedVCoreViewareaPtr :
    public PointerMField<VCoreViewarea *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGVCOREVIEWAREAFIELDS_H_ */
