/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGVCOREWORKERFIELDS_H_
#define _OSGVCOREWORKERFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGVCoreSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class VCoreWorker;

OSG_GEN_CONTAINERPTR(VCoreWorker);

/*! \ingroup GrpVCoreSystemFieldTraits
    \ingroup GrpLibOSGVCoreSystem
 */
template <>
struct FieldTraits<VCoreWorker *> :
    public FieldTraitsFCPtrBase<VCoreWorker *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<VCoreWorker *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCORESYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFVCoreWorkerPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFVCoreWorkerPtr"; }
};

template<> inline
const Char8 *FieldTraits<VCoreWorker *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecVCoreWorkerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreWorker *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecVCoreWorkerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreWorker *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakVCoreWorkerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreWorker *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdVCoreWorkerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreWorker *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecVCoreWorkerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreWorker *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecVCoreWorkerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreWorker *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakVCoreWorkerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreWorker *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdVCoreWorkerPtr"; 
}


/*! \ingroup GrpVCoreSystemFieldTraits
 */
template <>
struct FieldTraits<VCoreWorker *, 1> :
    public FieldTraitsFCPtrBase<VCoreWorker *, 1>
{
  private:

  public:
    typedef FieldTraits<VCoreWorker *, 1>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCORESYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);
};

template<> inline
const Char8 *FieldTraits<VCoreWorker *, 1>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecChildVCoreWorkerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreWorker *, 1>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecChildVCoreWorkerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreWorker *, 1>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakChildVCoreWorkerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreWorker *, 1>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdChildVCoreWorkerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreWorker *, 1>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecChildVCoreWorkerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreWorker *, 1>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecChildVCoreWorkerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreWorker *, 1>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakChildVCoreWorkerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreWorker *, 1>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdChildVCoreWorkerPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreWorker *,
                      RecordedRefCountPolicy  > SFRecVCoreWorkerPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreWorker *,
                      UnrecordedRefCountPolicy> SFUnrecVCoreWorkerPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreWorker *,
                      WeakRefCountPolicy      > SFWeakVCoreWorkerPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreWorker *,
                      NoRefCountPolicy        > SFUncountedVCoreWorkerPtr;


/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreWorker *,
                      RecordedRefCountPolicy  > MFRecVCoreWorkerPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreWorker *,
                      UnrecordedRefCountPolicy> MFUnrecVCoreWorkerPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreWorker *,
                      WeakRefCountPolicy      > MFWeakVCoreWorkerPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreWorker *,
                      NoRefCountPolicy        > MFUncountedVCoreWorkerPtr;



/*! \ingroup GrpVCoreSystemFieldSFields */
typedef ChildPointerSField<
          VCoreWorker *, 
          UnrecordedRefCountPolicy,
          1             > SFUnrecChildVCoreWorkerPtr;


/*! \ingroup GrpVCoreSystemFieldMFields */
typedef ChildPointerMField<
          VCoreWorker *, 
          UnrecordedRefCountPolicy,
          1             > MFUnrecChildVCoreWorkerPtr;



#else // these are the doxygen hacks

/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFRecVCoreWorkerPtr : 
    public PointerSField<VCoreWorker *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFUnrecVCoreWorkerPtr : 
    public PointerSField<VCoreWorker *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFWeakVCoreWorkerPtr :
    public PointerSField<VCoreWorker *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFUncountedVCoreWorkerPtr :
    public PointerSField<VCoreWorker *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFRecVCoreWorkerPtr :
    public PointerMField<VCoreWorker *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFUnrecVCoreWorkerPtr :
    public PointerMField<VCoreWorker *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFWeakVCoreWorkerPtr :
    public PointerMField<VCoreWorker *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFUncountedVCoreWorkerPtr :
    public PointerMField<VCoreWorker *,
                         NoRefCountPolicy        > {};



/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFUnrecChildVCoreWorkerPtr :
    public ChildPointerSField<
        VCoreWorker *, 
        UnrecordedRefCountPolicy,
        1             > {};


/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFUnrecChildVCoreWorkerPtr :
    public ChildPointerMField<
        VCoreWorker *, 
        UnrecordedRefCountPolicy,
        1             > {};


#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGVCOREWORKERFIELDS_H_ */
