/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGVCOREAPPFIELDS_H_
#define _OSGVCOREAPPFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGVCoreSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class VCoreApp;

OSG_GEN_CONTAINERPTR(VCoreApp);

/*! \ingroup GrpVCoreSystemFieldTraits
    \ingroup GrpLibOSGVCoreSystem
 */
template <>
struct FieldTraits<VCoreApp *> :
    public FieldTraitsFCPtrBase<VCoreApp *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<VCoreApp *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCORESYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFVCoreAppPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFVCoreAppPtr"; }
};

template<> inline
const Char8 *FieldTraits<VCoreApp *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecVCoreAppPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreApp *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecVCoreAppPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreApp *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakVCoreAppPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreApp *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdVCoreAppPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreApp *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecVCoreAppPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreApp *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecVCoreAppPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreApp *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakVCoreAppPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCoreApp *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdVCoreAppPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreApp *,
                      RecordedRefCountPolicy  > SFRecVCoreAppPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreApp *,
                      UnrecordedRefCountPolicy> SFUnrecVCoreAppPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreApp *,
                      WeakRefCountPolicy      > SFWeakVCoreAppPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<VCoreApp *,
                      NoRefCountPolicy        > SFUncountedVCoreAppPtr;


/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreApp *,
                      RecordedRefCountPolicy  > MFRecVCoreAppPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreApp *,
                      UnrecordedRefCountPolicy> MFUnrecVCoreAppPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreApp *,
                      WeakRefCountPolicy      > MFWeakVCoreAppPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<VCoreApp *,
                      NoRefCountPolicy        > MFUncountedVCoreAppPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFRecVCoreAppPtr : 
    public PointerSField<VCoreApp *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFUnrecVCoreAppPtr : 
    public PointerSField<VCoreApp *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFWeakVCoreAppPtr :
    public PointerSField<VCoreApp *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoreSystem */
struct SFUncountedVCoreAppPtr :
    public PointerSField<VCoreApp *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFRecVCoreAppPtr :
    public PointerMField<VCoreApp *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFUnrecVCoreAppPtr :
    public PointerMField<VCoreApp *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFWeakVCoreAppPtr :
    public PointerMField<VCoreApp *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoreSystem */
struct MFUncountedVCoreAppPtr :
    public PointerMField<VCoreApp *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGVCOREAPPFIELDS_H_ */
