/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class VCNativeWindow!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"




#include "OSGVCoREVCNativeWindowBase.h"
#include "OSGVCoREVCNativeWindow.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

VCORE_IMPORT_NAMESPACE;

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::VCNativeWindow
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<VCNativeWindow *, nsVCoRE>::_type(
    "VCNativeWindowPtr", 
    "VCWindowPtr", 
    VCNativeWindow::getClassType(),
    nsVCoRE);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(VCNativeWindow *, nsVCoRE)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           VCNativeWindow *,
                           nsVCoRE);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           VCNativeWindow *,
                           nsVCoRE);

OSG_END_NAMESPACE

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

void VCNativeWindowBase::classDescInserter(TypeObject &oType)
{
}


VCNativeWindowBase::TypeObject VCNativeWindowBase::_type(
    VCNativeWindowBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsVCoRE, //Namespace
    reinterpret_cast<PrototypeCreateF>(&VCNativeWindowBase::createEmptyLocal),
    VCNativeWindow::initMethod,
    VCNativeWindow::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&VCNativeWindow::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\" ?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"VCNativeWindow\"\n"
    "    parent=\"VCWindow\"\n"
    "    library=\"VCoRESystem\"\n"
    "    structure=\"concrete\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    isNodeCore=\"false\"\n"
    "    isBundle=\"true\"\n"
    "    docGroupBase=\"GrpVCoreSystem\"\n"
    "    libnamespace=\"VCoRE\"\n"
    "    >\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &VCNativeWindowBase::getType(void)
{
    return _type;
}

const FieldContainerType &VCNativeWindowBase::getType(void) const
{
    return _type;
}

UInt32 VCNativeWindowBase::getContainerSize(void) const
{
    return sizeof(VCNativeWindow);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

SizeT VCNativeWindowBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void VCNativeWindowBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void VCNativeWindowBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
VCNativeWindowTransitPtr VCNativeWindowBase::createLocal(BitVector bFlags)
{
    VCNativeWindowTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<VCNativeWindow>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
VCNativeWindowTransitPtr VCNativeWindowBase::createDependent(BitVector bFlags)
{
    VCNativeWindowTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<VCNativeWindow>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
VCNativeWindowTransitPtr VCNativeWindowBase::create(void)
{
    return createLocal();
}

VCNativeWindow *VCNativeWindowBase::createEmptyLocal(BitVector bFlags)
{
    VCNativeWindow *returnValue;

    newPtr<VCNativeWindow>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
VCNativeWindow *VCNativeWindowBase::createEmpty(void)
{
    return createEmptyLocal();
}


FieldContainerTransitPtr VCNativeWindowBase::shallowCopyLocal(
    BitVector bFlags) const
{
    VCNativeWindow *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const VCNativeWindow *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr VCNativeWindowBase::shallowCopyDependent(
    BitVector bFlags) const
{
    VCNativeWindow *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const VCNativeWindow *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr VCNativeWindowBase::shallowCopy(void) const
{
    return shallowCopyLocal();
}




/*------------------------- constructors ----------------------------------*/

VCNativeWindowBase::VCNativeWindowBase(void) :
    Inherited()
{
}

VCNativeWindowBase::VCNativeWindowBase(const VCNativeWindowBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

VCNativeWindowBase::~VCNativeWindowBase(void)
{
}



#ifdef OSG_MT_CPTR_ASPECT
void VCNativeWindowBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    VCNativeWindow *pThis = static_cast<VCNativeWindow *>(this);

    pThis->execSync(static_cast<VCNativeWindow *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *VCNativeWindowBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    VCNativeWindow *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const VCNativeWindow *>(pRefAspect),
                  dynamic_cast<const VCNativeWindow *>(this));

    return returnValue;
}
#endif

void VCNativeWindowBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


VCORE_END_NAMESPACE
