/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class VCGLUTViewer!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"




#include "OSGVCGLUTViewerBase.h"
#include "OSGVCGLUTViewer.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::VCGLUTViewer
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var Int32           VCGLUTViewerBase::_sfPostDFMixinTestField
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<VCGLUTViewer *>::_type("VCGLUTViewerPtr", "VCoreItemPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(VCGLUTViewer *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           VCGLUTViewer *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           VCGLUTViewer *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void VCGLUTViewerBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFInt32::Description(
        SFInt32::getClassType(),
        "postDFMixinTestField",
        "",
        PostDFMixinTestFieldFieldId, PostDFMixinTestFieldFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&VCGLUTViewer::editHandlePostDFMixinTestField),
        static_cast<FieldGetMethodSig >(&VCGLUTViewer::getHandlePostDFMixinTestField));

    oType.addInitialDesc(pDesc);
}


VCGLUTViewerBase::TypeObject VCGLUTViewerBase::_type(
    VCGLUTViewerBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&VCGLUTViewerBase::createEmptyLocal),
    VCGLUTViewer::initMethod,
    VCGLUTViewer::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&VCGLUTViewer::classDescInserter),
    true,
    0,
    "<?xml version=\"1.0\" ?>\n"
    "\n"
    "<FieldContainer\n"
    "   name=\"VCGLUTViewer\"\n"
    "   parent=\"VCoreItem\"\n"
    "   library=\"VCoreViewer\"\n"
    "   structure=\"concrete\"\n"
    "   pointerfieldtypes=\"both\"\n"
    "   systemcomponent=\"true\"\n"
    "   parentsystemcomponent=\"true\"\n"
    "   isNodeCore=\"true\"\n"
    "   docGroupBase=\"GrpVCoreViewer\"\n"
    "   typeDescAddable=\"true\"\n"
    "   dynFCDerived=\"true\"\n"
    "   >\n"
    "  <Field\n"
    "     name=\"postDFMixinTestField\"\n"
    "     type=\"Int32\"\n"
    "     cardinality=\"single\"\n"
    "     visibility=\"external\"\n"
    "     access=\"public\"\n"
    "     defaultValue=\"10\"\n"
    "     >\n"
    "  </Field>\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &VCGLUTViewerBase::getType(void)
{
    return _localType;
}

const FieldContainerType &VCGLUTViewerBase::getType(void) const
{
    return _localType;
}

UInt32 VCGLUTViewerBase::getContainerSize(void) const
{
    return sizeof(VCGLUTViewer);
}

VCGLUTViewerBase::TypeObject &VCGLUTViewerBase::getFinalType(void)
{
    return _type;
}

const VCGLUTViewerBase::TypeObject &VCGLUTViewerBase::getFinalType(void) const
{
    return _type;
}

/*------------------------- decorator get ------------------------------*/


SFInt32 *VCGLUTViewerBase::editSFPostDFMixinTestField(void)
{
    editSField(PostDFMixinTestFieldFieldMask);

    return &_sfPostDFMixinTestField;
}

const SFInt32 *VCGLUTViewerBase::getSFPostDFMixinTestField(void) const
{
    return &_sfPostDFMixinTestField;
}






/*------------------------------ access -----------------------------------*/

UInt32 VCGLUTViewerBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (PostDFMixinTestFieldFieldMask & whichField))
    {
        returnValue += _sfPostDFMixinTestField.getBinSize();
    }

    return returnValue;
}

void VCGLUTViewerBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (PostDFMixinTestFieldFieldMask & whichField))
    {
        _sfPostDFMixinTestField.copyToBin(pMem);
    }
}

void VCGLUTViewerBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (PostDFMixinTestFieldFieldMask & whichField))
    {
        editSField(PostDFMixinTestFieldFieldMask);
        _sfPostDFMixinTestField.copyFromBin(pMem);
    }
}

//! create a new instance of the class
VCGLUTViewerTransitPtr VCGLUTViewerBase::createLocal(BitVector bFlags)
{
    VCGLUTViewerTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<VCGLUTViewer>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
VCGLUTViewerTransitPtr VCGLUTViewerBase::createDependent(BitVector bFlags)
{
    VCGLUTViewerTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<VCGLUTViewer>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
VCGLUTViewerTransitPtr VCGLUTViewerBase::create(void)
{
    VCGLUTViewerTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<VCGLUTViewer>(tmpPtr);
    }

    return fc;
}

VCGLUTViewer *VCGLUTViewerBase::createEmptyLocal(BitVector bFlags)
{
    VCGLUTViewer *returnValue;

    newPtr<VCGLUTViewer>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
VCGLUTViewer *VCGLUTViewerBase::createEmpty(void)
{
    VCGLUTViewer *returnValue;

    newPtr<VCGLUTViewer>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr VCGLUTViewerBase::shallowCopyLocal(
    BitVector bFlags) const
{
    VCGLUTViewer *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const VCGLUTViewer *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr VCGLUTViewerBase::shallowCopyDependent(
    BitVector bFlags) const
{
    VCGLUTViewer *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const VCGLUTViewer *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr VCGLUTViewerBase::shallowCopy(void) const
{
    VCGLUTViewer *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const VCGLUTViewer *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

VCGLUTViewerBase::VCGLUTViewerBase(void) :
    Inherited(),
    _sfPostDFMixinTestField   (Int32(10))
{
}

VCGLUTViewerBase::VCGLUTViewerBase(const VCGLUTViewerBase &source) :
    Inherited(source),
    _sfPostDFMixinTestField   (source._sfPostDFMixinTestField   )
{
}


/*-------------------------- destructors ----------------------------------*/

VCGLUTViewerBase::~VCGLUTViewerBase(void)
{
}


GetFieldHandlePtr VCGLUTViewerBase::getHandlePostDFMixinTestField (void) const
{
    SFInt32::GetHandlePtr returnValue(
        new  SFInt32::GetHandle(
             &_sfPostDFMixinTestField,
             this->getType().getFieldDesc(PostDFMixinTestFieldFieldId),
             const_cast<VCGLUTViewerBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr VCGLUTViewerBase::editHandlePostDFMixinTestField(void)
{
    SFInt32::EditHandlePtr returnValue(
        new  SFInt32::EditHandle(
             &_sfPostDFMixinTestField,
             this->getType().getFieldDesc(PostDFMixinTestFieldFieldId),
             this));


    editSField(PostDFMixinTestFieldFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void VCGLUTViewerBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    VCGLUTViewer *pThis = static_cast<VCGLUTViewer *>(this);

    pThis->execSync(static_cast<VCGLUTViewer *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *VCGLUTViewerBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    VCGLUTViewer *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const VCGLUTViewer *>(pRefAspect),
                  dynamic_cast<const VCGLUTViewer *>(this));

    return returnValue;
}
#endif

void VCGLUTViewerBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
