/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGVCGLUTVIEWERFIELDS_H_
#define _OSGVCGLUTVIEWERFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGVCoreViewerDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class VCGLUTViewer;

OSG_GEN_CONTAINERPTR(VCGLUTViewer);

/*! \ingroup GrpVCoreViewerFieldTraits
    \ingroup GrpLibOSGVCoreViewer
 */
template <>
struct FieldTraits<VCGLUTViewer *> :
    public FieldTraitsFCPtrBase<VCGLUTViewer *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<VCGLUTViewer *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCOREVIEWER_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFVCGLUTViewerPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFVCGLUTViewerPtr"; }
};

template<> inline
const Char8 *FieldTraits<VCGLUTViewer *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecVCGLUTViewerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCGLUTViewer *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecVCGLUTViewerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCGLUTViewer *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakVCGLUTViewerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCGLUTViewer *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdVCGLUTViewerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCGLUTViewer *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecVCGLUTViewerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCGLUTViewer *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecVCGLUTViewerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCGLUTViewer *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakVCGLUTViewerPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCGLUTViewer *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdVCGLUTViewerPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVCoreViewerFieldSFields */
typedef PointerSField<VCGLUTViewer *,
                      RecordedRefCountPolicy  > SFRecVCGLUTViewerPtr;
/*! \ingroup GrpVCoreViewerFieldSFields */
typedef PointerSField<VCGLUTViewer *,
                      UnrecordedRefCountPolicy> SFUnrecVCGLUTViewerPtr;
/*! \ingroup GrpVCoreViewerFieldSFields */
typedef PointerSField<VCGLUTViewer *,
                      WeakRefCountPolicy      > SFWeakVCGLUTViewerPtr;
/*! \ingroup GrpVCoreViewerFieldSFields */
typedef PointerSField<VCGLUTViewer *,
                      NoRefCountPolicy        > SFUncountedVCGLUTViewerPtr;


/*! \ingroup GrpVCoreViewerFieldMFields */
typedef PointerMField<VCGLUTViewer *,
                      RecordedRefCountPolicy  > MFRecVCGLUTViewerPtr;
/*! \ingroup GrpVCoreViewerFieldMFields */
typedef PointerMField<VCGLUTViewer *,
                      UnrecordedRefCountPolicy> MFUnrecVCGLUTViewerPtr;
/*! \ingroup GrpVCoreViewerFieldMFields */
typedef PointerMField<VCGLUTViewer *,
                      WeakRefCountPolicy      > MFWeakVCGLUTViewerPtr;
/*! \ingroup GrpVCoreViewerFieldMFields */
typedef PointerMField<VCGLUTViewer *,
                      NoRefCountPolicy        > MFUncountedVCGLUTViewerPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpVCoreViewerFieldSFields \ingroup GrpLibOSGVCoreViewer */
struct SFRecVCGLUTViewerPtr : 
    public PointerSField<VCGLUTViewer *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreViewerFieldSFields \ingroup GrpLibOSGVCoreViewer */
struct SFUnrecVCGLUTViewerPtr : 
    public PointerSField<VCGLUTViewer *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreViewerFieldSFields \ingroup GrpLibOSGVCoreViewer */
struct SFWeakVCGLUTViewerPtr :
    public PointerSField<VCGLUTViewer *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVCoreViewerFieldSFields \ingroup GrpLibOSGVCoreViewer */
struct SFUncountedVCGLUTViewerPtr :
    public PointerSField<VCGLUTViewer *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVCoreViewerFieldMFields \ingroup GrpLibOSGVCoreViewer */
struct MFRecVCGLUTViewerPtr :
    public PointerMField<VCGLUTViewer *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVCoreViewerFieldMFields \ingroup GrpLibOSGVCoreViewer */
struct MFUnrecVCGLUTViewerPtr :
    public PointerMField<VCGLUTViewer *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreViewerFieldMFields \ingroup GrpLibOSGVCoreViewer */
struct MFWeakVCGLUTViewerPtr :
    public PointerMField<VCGLUTViewer *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVCoreViewerFieldMFields \ingroup GrpLibOSGVCoreViewer */
struct MFUncountedVCGLUTViewerPtr :
    public PointerMField<VCGLUTViewer *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGVCGLUTVIEWERFIELDS_H_ */
