/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGCSMITEMHANDLERFIELDS_H_
#define _OSGCSMITEMHANDLERFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGVCoRECSMDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

class CSMItemHandler;

OSG_GEN_CONTAINERPTR(CSMItemHandler);

VCORE_END_NAMESPACE

OSG_BEGIN_NAMESPACE

VCORE_IMPORT_NAMESPACE;
/*! \ingroup GrpVCoreCSMFieldTraits
    \ingroup GrpLibOSGVCoRECSM
 */
template <>
struct FieldTraits<CSMItemHandler *, nsVCoRE> :
    public FieldTraitsFCPtrBase<CSMItemHandler *, nsVCoRE>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<CSMItemHandler *, nsVCoRE>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCORECSM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<CSMItemHandler *, nsVCoRE>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecCSMItemHandlerPtr"; 
}

template<> inline
const Char8 *FieldTraits<CSMItemHandler *, nsVCoRE>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecCSMItemHandlerPtr"; 
}

template<> inline
const Char8 *FieldTraits<CSMItemHandler *, nsVCoRE>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakCSMItemHandlerPtr"; 
}

template<> inline
const Char8 *FieldTraits<CSMItemHandler *, nsVCoRE>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdCSMItemHandlerPtr"; 
}

template<> inline
const Char8 *FieldTraits<CSMItemHandler *, nsVCoRE>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecCSMItemHandlerPtr"; 
}

template<> inline
const Char8 *FieldTraits<CSMItemHandler *, nsVCoRE>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecCSMItemHandlerPtr"; 
}

template<> inline
const Char8 *FieldTraits<CSMItemHandler *, nsVCoRE>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakCSMItemHandlerPtr"; 
}

template<> inline
const Char8 *FieldTraits<CSMItemHandler *, nsVCoRE>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdCSMItemHandlerPtr"; 
}


OSG_END_NAMESPACE

VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVCoreCSMFieldSFields */
typedef PointerSField<CSMItemHandler *,
                      RecordedRefCountPolicy, nsVCoRE  > SFRecCSMItemHandlerPtr;
/*! \ingroup GrpVCoreCSMFieldSFields */
typedef PointerSField<CSMItemHandler *,
                      UnrecordedRefCountPolicy, nsVCoRE> SFUnrecCSMItemHandlerPtr;
/*! \ingroup GrpVCoreCSMFieldSFields */
typedef PointerSField<CSMItemHandler *,
                      WeakRefCountPolicy, nsVCoRE      > SFWeakCSMItemHandlerPtr;
/*! \ingroup GrpVCoreCSMFieldSFields */
typedef PointerSField<CSMItemHandler *,
                      NoRefCountPolicy, nsVCoRE        > SFUncountedCSMItemHandlerPtr;


/*! \ingroup GrpVCoreCSMFieldMFields */
typedef PointerMField<CSMItemHandler *,
                      RecordedRefCountPolicy, nsVCoRE  > MFRecCSMItemHandlerPtr;
/*! \ingroup GrpVCoreCSMFieldMFields */
typedef PointerMField<CSMItemHandler *,
                      UnrecordedRefCountPolicy, nsVCoRE> MFUnrecCSMItemHandlerPtr;
/*! \ingroup GrpVCoreCSMFieldMFields */
typedef PointerMField<CSMItemHandler *,
                      WeakRefCountPolicy, nsVCoRE      > MFWeakCSMItemHandlerPtr;
/*! \ingroup GrpVCoreCSMFieldMFields */
typedef PointerMField<CSMItemHandler *,
                      NoRefCountPolicy, nsVCoRE        > MFUncountedCSMItemHandlerPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpVCoreCSMFieldSFields \ingroup GrpLibOSGVCoRECSM */
struct SFRecCSMItemHandlerPtr : 
    public PointerSField<CSMItemHandler *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreCSMFieldSFields \ingroup GrpLibOSGVCoRECSM */
struct SFUnrecCSMItemHandlerPtr : 
    public PointerSField<CSMItemHandler *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreCSMFieldSFields \ingroup GrpLibOSGVCoRECSM */
struct SFWeakCSMItemHandlerPtr :
    public PointerSField<CSMItemHandler *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVCoreCSMFieldSFields \ingroup GrpLibOSGVCoRECSM */
struct SFUncountedCSMItemHandlerPtr :
    public PointerSField<CSMItemHandler *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVCoreCSMFieldMFields \ingroup GrpLibOSGVCoRECSM */
struct MFRecCSMItemHandlerPtr :
    public PointerMField<CSMItemHandler *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVCoreCSMFieldMFields \ingroup GrpLibOSGVCoRECSM */
struct MFUnrecCSMItemHandlerPtr :
    public PointerMField<CSMItemHandler *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreCSMFieldMFields \ingroup GrpLibOSGVCoRECSM */
struct MFWeakCSMItemHandlerPtr :
    public PointerMField<CSMItemHandler *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVCoreCSMFieldMFields \ingroup GrpLibOSGVCoRECSM */
struct MFUncountedCSMItemHandlerPtr :
    public PointerMField<CSMItemHandler *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

VCORE_END_NAMESPACE

#endif /* _OSGCSMITEMHANDLERFIELDS_H_ */
