/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGOSGTREEITEMFIELDS_H_
#define _OSGOSGTREEITEMFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGVCoRECSMDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

class OSGTreeItem;

OSG_GEN_CONTAINERPTR(OSGTreeItem);

VCORE_END_NAMESPACE

OSG_BEGIN_NAMESPACE

VCORE_IMPORT_NAMESPACE;
/*! \ingroup GrpVCoreCSMFieldTraits
    \ingroup GrpLibOSGVCoRECSM
 */
template <>
struct FieldTraits<OSGTreeItem *, nsVCoRE> :
    public FieldTraitsFCPtrBase<OSGTreeItem *, nsVCoRE>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<OSGTreeItem *, nsVCoRE>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCORECSM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<OSGTreeItem *, nsVCoRE>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecOSGTreeItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<OSGTreeItem *, nsVCoRE>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecOSGTreeItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<OSGTreeItem *, nsVCoRE>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakOSGTreeItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<OSGTreeItem *, nsVCoRE>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdOSGTreeItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<OSGTreeItem *, nsVCoRE>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecOSGTreeItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<OSGTreeItem *, nsVCoRE>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecOSGTreeItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<OSGTreeItem *, nsVCoRE>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakOSGTreeItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<OSGTreeItem *, nsVCoRE>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdOSGTreeItemPtr"; 
}


/*! \ingroup GrpVCoreCSMFieldTraits
 */
template <>
struct FieldTraits<OSGTreeItem *, nsVCoRE + 1> : 
    public FieldTraitsFCPtrBase<OSGTreeItem *, nsVCoRE + 1>
{
  private:

    static  DataType                                _type;

  public:

    static const bool bIsPointerField = true;

    typedef FieldTraits<OSGTreeItem *, nsVCoRE + 1> Self;


    enum             { Convertible = Self::NotConvertible };
    
    static OSG_VCORECSM_DLLMAPPING
                 DataType &getType (void);

    static const Char8    *getSName(void) 
    {
        return "SFParentOSGTreeItemPtr"; 
    }

    static const Char8    *getMName(void) 
    { 
        return "MFParentOSGTreeItemPtr"; 
    }
};

OSG_END_NAMESPACE

VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVCoreCSMFieldSFields */
typedef PointerSField<OSGTreeItem *,
                      RecordedRefCountPolicy, nsVCoRE  > SFRecOSGTreeItemPtr;
/*! \ingroup GrpVCoreCSMFieldSFields */
typedef PointerSField<OSGTreeItem *,
                      UnrecordedRefCountPolicy, nsVCoRE> SFUnrecOSGTreeItemPtr;
/*! \ingroup GrpVCoreCSMFieldSFields */
typedef PointerSField<OSGTreeItem *,
                      WeakRefCountPolicy, nsVCoRE      > SFWeakOSGTreeItemPtr;
/*! \ingroup GrpVCoreCSMFieldSFields */
typedef PointerSField<OSGTreeItem *,
                      NoRefCountPolicy, nsVCoRE        > SFUncountedOSGTreeItemPtr;


/*! \ingroup GrpVCoreCSMFieldMFields */
typedef PointerMField<OSGTreeItem *,
                      RecordedRefCountPolicy, nsVCoRE  > MFRecOSGTreeItemPtr;
/*! \ingroup GrpVCoreCSMFieldMFields */
typedef PointerMField<OSGTreeItem *,
                      UnrecordedRefCountPolicy, nsVCoRE> MFUnrecOSGTreeItemPtr;
/*! \ingroup GrpVCoreCSMFieldMFields */
typedef PointerMField<OSGTreeItem *,
                      WeakRefCountPolicy, nsVCoRE      > MFWeakOSGTreeItemPtr;
/*! \ingroup GrpVCoreCSMFieldMFields */
typedef PointerMField<OSGTreeItem *,
                      NoRefCountPolicy, nsVCoRE        > MFUncountedOSGTreeItemPtr;



/*! \ingroup GrpVCoreCSMFieldSFields */
typedef ParentPointerSField<
          OSGTreeItem *, 
          NoRefCountPolicy,
          nsVCoRE + 1    > SFParentOSGTreeItemPtr;


#else // these are the doxygen hacks

/*! \ingroup GrpVCoreCSMFieldSFields \ingroup GrpLibOSGVCoRECSM */
struct SFRecOSGTreeItemPtr : 
    public PointerSField<OSGTreeItem *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreCSMFieldSFields \ingroup GrpLibOSGVCoRECSM */
struct SFUnrecOSGTreeItemPtr : 
    public PointerSField<OSGTreeItem *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreCSMFieldSFields \ingroup GrpLibOSGVCoRECSM */
struct SFWeakOSGTreeItemPtr :
    public PointerSField<OSGTreeItem *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVCoreCSMFieldSFields \ingroup GrpLibOSGVCoRECSM */
struct SFUncountedOSGTreeItemPtr :
    public PointerSField<OSGTreeItem *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVCoreCSMFieldMFields \ingroup GrpLibOSGVCoRECSM */
struct MFRecOSGTreeItemPtr :
    public PointerMField<OSGTreeItem *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVCoreCSMFieldMFields \ingroup GrpLibOSGVCoRECSM */
struct MFUnrecOSGTreeItemPtr :
    public PointerMField<OSGTreeItem *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreCSMFieldMFields \ingroup GrpLibOSGVCoRECSM */
struct MFWeakOSGTreeItemPtr :
    public PointerMField<OSGTreeItem *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVCoreCSMFieldMFields \ingroup GrpLibOSGVCoRECSM */
struct MFUncountedOSGTreeItemPtr :
    public PointerMField<OSGTreeItem *,
                         NoRefCountPolicy        > {};



/*! \ingroup GrpVCoreCSMFieldSFields \ingroup GrpLibOSGVCoRECSM */
struct SFParentOSGTreeItemPtr :
    public ParentPointerSField<
        OSGTreeItem *, 
        NoRefCountPolicy,
        nsVCoRE + 1    > {};

#endif // these are the doxygen hacks

VCORE_END_NAMESPACE

#endif /* _OSGOSGTREEITEMFIELDS_H_ */
