/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class OSGBaseItem!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"




#include "OSGVCoREOSGBaseItemBase.h"
#include "OSGVCoREOSGBaseItem.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

VCORE_IMPORT_NAMESPACE;

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::OSGBaseItem
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<OSGBaseItem *, nsVCoRE>::_type(
    "OSGBaseItemPtr", 
    "ItemPtr", 
    OSGBaseItem::getClassType(),
    nsVCoRE);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(OSGBaseItem *, nsVCoRE)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           OSGBaseItem *,
                           nsVCoRE);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           OSGBaseItem *,
                           nsVCoRE);

DataType &FieldTraits< OSGBaseItem *, nsVCoRE + 1 >::getType(void)
{
    return FieldTraits<OSGBaseItem *, nsVCoRE>::getType();
}


OSG_EXPORT_PTR_SFIELD(ChildPointerSField,
                      OSGBaseItem *,
                      UnrecordedRefCountPolicy,
                      nsVCoRE + 1);


OSG_EXPORT_PTR_MFIELD(ChildPointerMField,
                      OSGBaseItem *,
                      UnrecordedRefCountPolicy,
                      nsVCoRE + 1);


DataType &FieldTraits<OSGBaseItem *, nsVCoRE + 2 >::getType(void)
{
    return FieldTraits<OSGBaseItem *, nsVCoRE>::getType();
}


OSG_SFIELDTYPE_INST(ParentPointerSField,
                    OSGBaseItem *,
                    NoRefCountPolicy,
                    nsVCoRE + 2);

OSG_FIELD_DLLEXPORT_DEF3(ParentPointerSField,
                         OSGBaseItem *,
                         NoRefCountPolicy,
                         nsVCoRE + 2);


OSG_END_NAMESPACE

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

void OSGBaseItemBase::classDescInserter(TypeObject &oType)
{
}


OSGBaseItemBase::TypeObject OSGBaseItemBase::_type(
    OSGBaseItemBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsVCoRE, //Namespace
    NULL,
    OSGBaseItem::initMethod,
    OSGBaseItem::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&OSGBaseItem::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\" ?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"OSGBaseItem\"\n"
    "    parent=\"Item\"\n"
    "    library=\"VCoRECSM\"\n"
    "    structure=\"abstract\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    docGroupBase=\"GrpVCoreCSM\"\n"
    "    parentFields=\"single\"\n"
    "    childFields=\"both\"\n"
    "    libnamespace=\"VCoRE\"\n"
    "   >\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &OSGBaseItemBase::getType(void)
{
    return _type;
}

const FieldContainerType &OSGBaseItemBase::getType(void) const
{
    return _type;
}

UInt32 OSGBaseItemBase::getContainerSize(void) const
{
    return sizeof(OSGBaseItem);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

SizeT OSGBaseItemBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void OSGBaseItemBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void OSGBaseItemBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}




/*------------------------- constructors ----------------------------------*/

OSGBaseItemBase::OSGBaseItemBase(void) :
    Inherited()
{
}

OSGBaseItemBase::OSGBaseItemBase(const OSGBaseItemBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

OSGBaseItemBase::~OSGBaseItemBase(void)
{
}



#ifdef OSG_MT_CPTR_ASPECT
void OSGBaseItemBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    OSGBaseItem *pThis = static_cast<OSGBaseItem *>(this);

    pThis->execSync(static_cast<OSGBaseItem *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif



void OSGBaseItemBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


VCORE_END_NAMESPACE
