/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGCSMITEMFIELDS_H_
#define _OSGCSMITEMFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGVCoRECSMDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

class CSMItem;

OSG_GEN_CONTAINERPTR(CSMItem);

VCORE_END_NAMESPACE

OSG_BEGIN_NAMESPACE

VCORE_IMPORT_NAMESPACE;
/*! \ingroup GrpVCoreCSMFieldTraits
    \ingroup GrpLibOSGVCoRECSM
 */
template <>
struct FieldTraits<CSMItem *, nsVCoRE> :
    public FieldTraitsFCPtrBase<CSMItem *, nsVCoRE>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<CSMItem *, nsVCoRE>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCORECSM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<CSMItem *, nsVCoRE>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecCSMItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<CSMItem *, nsVCoRE>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecCSMItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<CSMItem *, nsVCoRE>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakCSMItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<CSMItem *, nsVCoRE>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdCSMItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<CSMItem *, nsVCoRE>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecCSMItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<CSMItem *, nsVCoRE>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecCSMItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<CSMItem *, nsVCoRE>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakCSMItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<CSMItem *, nsVCoRE>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdCSMItemPtr"; 
}


/*! \ingroup GrpVCoreCSMFieldTraits
 */
template <>
struct FieldTraits<CSMItem *, nsVCoRE + 1> : 
    public FieldTraitsFCPtrBase<CSMItem *, nsVCoRE + 1>
{
  private:

    static  DataType                                _type;

  public:

    static const bool bIsPointerField = true;

    typedef FieldTraits<CSMItem *, nsVCoRE + 1> Self;


    enum             { Convertible = Self::NotConvertible };
    
    static OSG_VCORECSM_DLLMAPPING
                 DataType &getType (void);

    static const Char8    *getSName(void) 
    {
        return "SFParentCSMItemPtr"; 
    }

    static const Char8    *getMName(void) 
    { 
        return "MFParentCSMItemPtr"; 
    }
};

OSG_END_NAMESPACE

VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVCoreCSMFieldSFields */
typedef PointerSField<CSMItem *,
                      RecordedRefCountPolicy, nsVCoRE  > SFRecCSMItemPtr;
/*! \ingroup GrpVCoreCSMFieldSFields */
typedef PointerSField<CSMItem *,
                      UnrecordedRefCountPolicy, nsVCoRE> SFUnrecCSMItemPtr;
/*! \ingroup GrpVCoreCSMFieldSFields */
typedef PointerSField<CSMItem *,
                      WeakRefCountPolicy, nsVCoRE      > SFWeakCSMItemPtr;
/*! \ingroup GrpVCoreCSMFieldSFields */
typedef PointerSField<CSMItem *,
                      NoRefCountPolicy, nsVCoRE        > SFUncountedCSMItemPtr;


/*! \ingroup GrpVCoreCSMFieldMFields */
typedef PointerMField<CSMItem *,
                      RecordedRefCountPolicy, nsVCoRE  > MFRecCSMItemPtr;
/*! \ingroup GrpVCoreCSMFieldMFields */
typedef PointerMField<CSMItem *,
                      UnrecordedRefCountPolicy, nsVCoRE> MFUnrecCSMItemPtr;
/*! \ingroup GrpVCoreCSMFieldMFields */
typedef PointerMField<CSMItem *,
                      WeakRefCountPolicy, nsVCoRE      > MFWeakCSMItemPtr;
/*! \ingroup GrpVCoreCSMFieldMFields */
typedef PointerMField<CSMItem *,
                      NoRefCountPolicy, nsVCoRE        > MFUncountedCSMItemPtr;



/*! \ingroup GrpVCoreCSMFieldSFields */
typedef ParentPointerSField<
          CSMItem *, 
          NoRefCountPolicy,
          nsVCoRE + 1    > SFParentCSMItemPtr;


#else // these are the doxygen hacks

/*! \ingroup GrpVCoreCSMFieldSFields \ingroup GrpLibOSGVCoRECSM */
struct SFRecCSMItemPtr : 
    public PointerSField<CSMItem *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreCSMFieldSFields \ingroup GrpLibOSGVCoRECSM */
struct SFUnrecCSMItemPtr : 
    public PointerSField<CSMItem *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreCSMFieldSFields \ingroup GrpLibOSGVCoRECSM */
struct SFWeakCSMItemPtr :
    public PointerSField<CSMItem *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVCoreCSMFieldSFields \ingroup GrpLibOSGVCoRECSM */
struct SFUncountedCSMItemPtr :
    public PointerSField<CSMItem *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVCoreCSMFieldMFields \ingroup GrpLibOSGVCoRECSM */
struct MFRecCSMItemPtr :
    public PointerMField<CSMItem *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVCoreCSMFieldMFields \ingroup GrpLibOSGVCoRECSM */
struct MFUnrecCSMItemPtr :
    public PointerMField<CSMItem *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreCSMFieldMFields \ingroup GrpLibOSGVCoRECSM */
struct MFWeakCSMItemPtr :
    public PointerMField<CSMItem *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVCoreCSMFieldMFields \ingroup GrpLibOSGVCoRECSM */
struct MFUncountedCSMItemPtr :
    public PointerMField<CSMItem *,
                         NoRefCountPolicy        > {};



/*! \ingroup GrpVCoreCSMFieldSFields \ingroup GrpLibOSGVCoRECSM */
struct SFParentCSMItemPtr :
    public ParentPointerSField<
        CSMItem *, 
        NoRefCountPolicy,
        nsVCoRE + 1    > {};

#endif // these are the doxygen hacks

VCORE_END_NAMESPACE

#endif /* _OSGCSMITEMFIELDS_H_ */
