/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSTAGEDVIEWPORTFIELDS_H_
#define _OSGSTAGEDVIEWPORTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGVCoREGreatestHacksDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class StagedViewport;

OSG_GEN_CONTAINERPTR(StagedViewport);
/*! \ingroup GrpVCoreGreatestHacksFieldTraits
    \ingroup GrpLibOSGVCoREGreatestHacks
 */
template <>
struct FieldTraits<StagedViewport *, nsOSG> :
    public FieldTraitsFCPtrBase<StagedViewport *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<StagedViewport *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCOREGREATESTHACKS_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<StagedViewport *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecStagedViewportPtr"; 
}

template<> inline
const Char8 *FieldTraits<StagedViewport *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecStagedViewportPtr"; 
}

template<> inline
const Char8 *FieldTraits<StagedViewport *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakStagedViewportPtr"; 
}

template<> inline
const Char8 *FieldTraits<StagedViewport *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdStagedViewportPtr"; 
}

template<> inline
const Char8 *FieldTraits<StagedViewport *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecStagedViewportPtr"; 
}

template<> inline
const Char8 *FieldTraits<StagedViewport *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecStagedViewportPtr"; 
}

template<> inline
const Char8 *FieldTraits<StagedViewport *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakStagedViewportPtr"; 
}

template<> inline
const Char8 *FieldTraits<StagedViewport *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdStagedViewportPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVCoreGreatestHacksFieldSFields */
typedef PointerSField<StagedViewport *,
                      RecordedRefCountPolicy, nsOSG  > SFRecStagedViewportPtr;
/*! \ingroup GrpVCoreGreatestHacksFieldSFields */
typedef PointerSField<StagedViewport *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecStagedViewportPtr;
/*! \ingroup GrpVCoreGreatestHacksFieldSFields */
typedef PointerSField<StagedViewport *,
                      WeakRefCountPolicy, nsOSG      > SFWeakStagedViewportPtr;
/*! \ingroup GrpVCoreGreatestHacksFieldSFields */
typedef PointerSField<StagedViewport *,
                      NoRefCountPolicy, nsOSG        > SFUncountedStagedViewportPtr;


/*! \ingroup GrpVCoreGreatestHacksFieldMFields */
typedef PointerMField<StagedViewport *,
                      RecordedRefCountPolicy, nsOSG  > MFRecStagedViewportPtr;
/*! \ingroup GrpVCoreGreatestHacksFieldMFields */
typedef PointerMField<StagedViewport *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecStagedViewportPtr;
/*! \ingroup GrpVCoreGreatestHacksFieldMFields */
typedef PointerMField<StagedViewport *,
                      WeakRefCountPolicy, nsOSG      > MFWeakStagedViewportPtr;
/*! \ingroup GrpVCoreGreatestHacksFieldMFields */
typedef PointerMField<StagedViewport *,
                      NoRefCountPolicy, nsOSG        > MFUncountedStagedViewportPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpVCoreGreatestHacksFieldSFields \ingroup GrpLibOSGVCoREGreatestHacks */
struct SFRecStagedViewportPtr : 
    public PointerSField<StagedViewport *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreGreatestHacksFieldSFields \ingroup GrpLibOSGVCoREGreatestHacks */
struct SFUnrecStagedViewportPtr : 
    public PointerSField<StagedViewport *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreGreatestHacksFieldSFields \ingroup GrpLibOSGVCoREGreatestHacks */
struct SFWeakStagedViewportPtr :
    public PointerSField<StagedViewport *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVCoreGreatestHacksFieldSFields \ingroup GrpLibOSGVCoREGreatestHacks */
struct SFUncountedStagedViewportPtr :
    public PointerSField<StagedViewport *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVCoreGreatestHacksFieldMFields \ingroup GrpLibOSGVCoREGreatestHacks */
struct MFRecStagedViewportPtr :
    public PointerMField<StagedViewport *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVCoreGreatestHacksFieldMFields \ingroup GrpLibOSGVCoREGreatestHacks */
struct MFUnrecStagedViewportPtr :
    public PointerMField<StagedViewport *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreGreatestHacksFieldMFields \ingroup GrpLibOSGVCoREGreatestHacks */
struct MFWeakStagedViewportPtr :
    public PointerMField<StagedViewport *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVCoreGreatestHacksFieldMFields \ingroup GrpLibOSGVCoREGreatestHacks */
struct MFUncountedStagedViewportPtr :
    public PointerMField<StagedViewport *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGSTAGEDVIEWPORTFIELDS_H_ */
