/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGVCTESTSTAGEFIELDS_H_
#define _OSGVCTESTSTAGEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGVCoREGreatestHacksDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class VCTestStage;

OSG_GEN_CONTAINERPTR(VCTestStage);
/*! \ingroup GrpVCoreGreatestHacksFieldTraits
    \ingroup GrpLibOSGVCoREGreatestHacks
 */
template <>
struct FieldTraits<VCTestStage *, nsOSG> :
    public FieldTraitsFCPtrBase<VCTestStage *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<VCTestStage *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCOREGREATESTHACKS_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<VCTestStage *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecVCTestStagePtr"; 
}

template<> inline
const Char8 *FieldTraits<VCTestStage *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecVCTestStagePtr"; 
}

template<> inline
const Char8 *FieldTraits<VCTestStage *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakVCTestStagePtr"; 
}

template<> inline
const Char8 *FieldTraits<VCTestStage *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdVCTestStagePtr"; 
}

template<> inline
const Char8 *FieldTraits<VCTestStage *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecVCTestStagePtr"; 
}

template<> inline
const Char8 *FieldTraits<VCTestStage *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecVCTestStagePtr"; 
}

template<> inline
const Char8 *FieldTraits<VCTestStage *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakVCTestStagePtr"; 
}

template<> inline
const Char8 *FieldTraits<VCTestStage *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdVCTestStagePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVCoreGreatestHacksFieldSFields */
typedef PointerSField<VCTestStage *,
                      RecordedRefCountPolicy, nsOSG  > SFRecVCTestStagePtr;
/*! \ingroup GrpVCoreGreatestHacksFieldSFields */
typedef PointerSField<VCTestStage *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecVCTestStagePtr;
/*! \ingroup GrpVCoreGreatestHacksFieldSFields */
typedef PointerSField<VCTestStage *,
                      WeakRefCountPolicy, nsOSG      > SFWeakVCTestStagePtr;
/*! \ingroup GrpVCoreGreatestHacksFieldSFields */
typedef PointerSField<VCTestStage *,
                      NoRefCountPolicy, nsOSG        > SFUncountedVCTestStagePtr;


/*! \ingroup GrpVCoreGreatestHacksFieldMFields */
typedef PointerMField<VCTestStage *,
                      RecordedRefCountPolicy, nsOSG  > MFRecVCTestStagePtr;
/*! \ingroup GrpVCoreGreatestHacksFieldMFields */
typedef PointerMField<VCTestStage *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecVCTestStagePtr;
/*! \ingroup GrpVCoreGreatestHacksFieldMFields */
typedef PointerMField<VCTestStage *,
                      WeakRefCountPolicy, nsOSG      > MFWeakVCTestStagePtr;
/*! \ingroup GrpVCoreGreatestHacksFieldMFields */
typedef PointerMField<VCTestStage *,
                      NoRefCountPolicy, nsOSG        > MFUncountedVCTestStagePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpVCoreGreatestHacksFieldSFields \ingroup GrpLibOSGVCoREGreatestHacks */
struct SFRecVCTestStagePtr : 
    public PointerSField<VCTestStage *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreGreatestHacksFieldSFields \ingroup GrpLibOSGVCoREGreatestHacks */
struct SFUnrecVCTestStagePtr : 
    public PointerSField<VCTestStage *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreGreatestHacksFieldSFields \ingroup GrpLibOSGVCoREGreatestHacks */
struct SFWeakVCTestStagePtr :
    public PointerSField<VCTestStage *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVCoreGreatestHacksFieldSFields \ingroup GrpLibOSGVCoREGreatestHacks */
struct SFUncountedVCTestStagePtr :
    public PointerSField<VCTestStage *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVCoreGreatestHacksFieldMFields \ingroup GrpLibOSGVCoREGreatestHacks */
struct MFRecVCTestStagePtr :
    public PointerMField<VCTestStage *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVCoreGreatestHacksFieldMFields \ingroup GrpLibOSGVCoREGreatestHacks */
struct MFUnrecVCTestStagePtr :
    public PointerMField<VCTestStage *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreGreatestHacksFieldMFields \ingroup GrpLibOSGVCoREGreatestHacks */
struct MFWeakVCTestStagePtr :
    public PointerMField<VCTestStage *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVCoreGreatestHacksFieldMFields \ingroup GrpLibOSGVCoREGreatestHacks */
struct MFUncountedVCTestStagePtr :
    public PointerMField<VCTestStage *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGVCTESTSTAGEFIELDS_H_ */
