/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class OSGTestSceneItem!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"




#include "OSGVCoREOSGTestSceneItemBase.h"
#include "OSGVCoREOSGTestSceneItem.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

VCORE_IMPORT_NAMESPACE;

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::OSGTestSceneItem
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var Real32          OSGTestSceneItemBase::_sfRotationSpeed
    
*/

/*! \var bool            OSGTestSceneItemBase::_sfAnimate
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<OSGTestSceneItem *, nsVCoRE>::_type(
    "OSGTestSceneItemPtr", 
    "OSGTreeItemPtr", 
    OSGTestSceneItem::getClassType(),
    nsVCoRE);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(OSGTestSceneItem *, nsVCoRE)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           OSGTestSceneItem *,
                           nsVCoRE);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           OSGTestSceneItem *,
                           nsVCoRE);

OSG_END_NAMESPACE

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

void OSGTestSceneItemBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFReal32::Description(
        SFReal32::getClassType(),
        "rotationSpeed",
        "",
        RotationSpeedFieldId, RotationSpeedFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&OSGTestSceneItem::editHandleRotationSpeed),
        static_cast<FieldGetMethodSig >(&OSGTestSceneItem::getHandleRotationSpeed));

    oType.addInitialDesc(pDesc);

    pDesc = new SFBool::Description(
        SFBool::getClassType(),
        "animate",
        "",
        AnimateFieldId, AnimateFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&OSGTestSceneItem::editHandleAnimate),
        static_cast<FieldGetMethodSig >(&OSGTestSceneItem::getHandleAnimate));

    oType.addInitialDesc(pDesc);
}


OSGTestSceneItemBase::TypeObject OSGTestSceneItemBase::_type(
    OSGTestSceneItemBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsVCoRE, //Namespace
    reinterpret_cast<PrototypeCreateF>(&OSGTestSceneItemBase::createEmptyLocal),
    OSGTestSceneItem::initMethod,
    OSGTestSceneItem::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&OSGTestSceneItem::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\" ?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"OSGTestSceneItem\"\n"
    "    parent=\"OSGTreeItem\"\n"
    "    library=\"VCoRETest\"\n"
    "    structure=\"concrete\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    isNodeCore=\"false\"\n"
    "    isBundle=\"true\"\n"
    "    docGroupBase=\"GrpVCoreSystem\"\n"
    "    libnamespace=\"VCoRE\"\n"
    "    >\n"
    "  <Field\n"
    "\t name=\"rotationSpeed\"\n"
    "\t type=\"Real32\"\n"
    "\t cardinality=\"single\"\n"
    "\t defaultValue=\"1.0f\"\n"
    "\t access=\"public\"\n"
    "\t >\n"
    "  </Field>\n"
    "  <Field\n"
    "\t name=\"animate\"\n"
    "\t type=\"bool\"\n"
    "\t cardinality=\"single\"\n"
    "\t defaultValue=\"true\"\n"
    "\t access=\"public\"\n"
    "\t >\n"
    "  </Field>\n"
    "\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &OSGTestSceneItemBase::getType(void)
{
    return _type;
}

const FieldContainerType &OSGTestSceneItemBase::getType(void) const
{
    return _type;
}

UInt32 OSGTestSceneItemBase::getContainerSize(void) const
{
    return sizeof(OSGTestSceneItem);
}

/*------------------------- decorator get ------------------------------*/


SFReal32 *OSGTestSceneItemBase::editSFRotationSpeed(void)
{
    editSField(RotationSpeedFieldMask);

    return &_sfRotationSpeed;
}

const SFReal32 *OSGTestSceneItemBase::getSFRotationSpeed(void) const
{
    return &_sfRotationSpeed;
}


SFBool *OSGTestSceneItemBase::editSFAnimate(void)
{
    editSField(AnimateFieldMask);

    return &_sfAnimate;
}

const SFBool *OSGTestSceneItemBase::getSFAnimate(void) const
{
    return &_sfAnimate;
}






/*------------------------------ access -----------------------------------*/

SizeT OSGTestSceneItemBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (RotationSpeedFieldMask & whichField))
    {
        returnValue += _sfRotationSpeed.getBinSize();
    }
    if(FieldBits::NoField != (AnimateFieldMask & whichField))
    {
        returnValue += _sfAnimate.getBinSize();
    }

    return returnValue;
}

void OSGTestSceneItemBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (RotationSpeedFieldMask & whichField))
    {
        _sfRotationSpeed.copyToBin(pMem);
    }
    if(FieldBits::NoField != (AnimateFieldMask & whichField))
    {
        _sfAnimate.copyToBin(pMem);
    }
}

void OSGTestSceneItemBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (RotationSpeedFieldMask & whichField))
    {
        editSField(RotationSpeedFieldMask);
        _sfRotationSpeed.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (AnimateFieldMask & whichField))
    {
        editSField(AnimateFieldMask);
        _sfAnimate.copyFromBin(pMem);
    }
}

//! create a new instance of the class
OSGTestSceneItemTransitPtr OSGTestSceneItemBase::createLocal(BitVector bFlags)
{
    OSGTestSceneItemTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<OSGTestSceneItem>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
OSGTestSceneItemTransitPtr OSGTestSceneItemBase::createDependent(BitVector bFlags)
{
    OSGTestSceneItemTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<OSGTestSceneItem>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
OSGTestSceneItemTransitPtr OSGTestSceneItemBase::create(void)
{
    return createLocal();
}

OSGTestSceneItem *OSGTestSceneItemBase::createEmptyLocal(BitVector bFlags)
{
    OSGTestSceneItem *returnValue;

    newPtr<OSGTestSceneItem>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
OSGTestSceneItem *OSGTestSceneItemBase::createEmpty(void)
{
    return createEmptyLocal();
}


FieldContainerTransitPtr OSGTestSceneItemBase::shallowCopyLocal(
    BitVector bFlags) const
{
    OSGTestSceneItem *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const OSGTestSceneItem *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr OSGTestSceneItemBase::shallowCopyDependent(
    BitVector bFlags) const
{
    OSGTestSceneItem *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const OSGTestSceneItem *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr OSGTestSceneItemBase::shallowCopy(void) const
{
    return shallowCopyLocal();
}




/*------------------------- constructors ----------------------------------*/

OSGTestSceneItemBase::OSGTestSceneItemBase(void) :
    Inherited(),
    _sfRotationSpeed          (Real32(1.0f)),
    _sfAnimate                (bool(true))
{
}

OSGTestSceneItemBase::OSGTestSceneItemBase(const OSGTestSceneItemBase &source) :
    Inherited(source),
    _sfRotationSpeed          (source._sfRotationSpeed          ),
    _sfAnimate                (source._sfAnimate                )
{
}


/*-------------------------- destructors ----------------------------------*/

OSGTestSceneItemBase::~OSGTestSceneItemBase(void)
{
}


GetFieldHandlePtr OSGTestSceneItemBase::getHandleRotationSpeed   (void) const
{
    SFReal32::GetHandlePtr returnValue(
        new  SFReal32::GetHandle(
             &_sfRotationSpeed,
             this->getType().getFieldDesc(RotationSpeedFieldId),
             const_cast<OSGTestSceneItemBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr OSGTestSceneItemBase::editHandleRotationSpeed  (void)
{
    SFReal32::EditHandlePtr returnValue(
        new  SFReal32::EditHandle(
             &_sfRotationSpeed,
             this->getType().getFieldDesc(RotationSpeedFieldId),
             this));


    editSField(RotationSpeedFieldMask);

    return returnValue;
}

GetFieldHandlePtr OSGTestSceneItemBase::getHandleAnimate         (void) const
{
    SFBool::GetHandlePtr returnValue(
        new  SFBool::GetHandle(
             &_sfAnimate,
             this->getType().getFieldDesc(AnimateFieldId),
             const_cast<OSGTestSceneItemBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr OSGTestSceneItemBase::editHandleAnimate        (void)
{
    SFBool::EditHandlePtr returnValue(
        new  SFBool::EditHandle(
             &_sfAnimate,
             this->getType().getFieldDesc(AnimateFieldId),
             this));


    editSField(AnimateFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void OSGTestSceneItemBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    OSGTestSceneItem *pThis = static_cast<OSGTestSceneItem *>(this);

    pThis->execSync(static_cast<OSGTestSceneItem *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *OSGTestSceneItemBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    OSGTestSceneItem *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const OSGTestSceneItem *>(pRefAspect),
                  dynamic_cast<const OSGTestSceneItem *>(this));

    return returnValue;
}
#endif

void OSGTestSceneItemBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


VCORE_END_NAMESPACE
