/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class OSGTestSceneItem!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"



#include "OSGNode.h"                    // Root Class
#include "OSGFieldContainer.h"          // Globals Class
#include "OSGCamera.h"                  // Camera Class

#include "OSGVCoREOSGTestSceneItemBase.h"
#include "OSGVCoREOSGTestSceneItem.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

VCORE_IMPORT_NAMESPACE;

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::OSGTestSceneItem
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var std::string     OSGTestSceneItemBase::_mfUrl
    
*/

/*! \var std::string     OSGTestSceneItemBase::_sfMatchedUrl
    
*/

/*! \var Node *          OSGTestSceneItemBase::_sfRoot
    
*/

/*! \var FieldContainer * OSGTestSceneItemBase::_mfGlobals
    
*/

/*! \var std::string     OSGTestSceneItemBase::_mfGlobalUrl
    
*/

/*! \var std::string     OSGTestSceneItemBase::_sfMatchedGlobalUrl
    
*/

/*! \var Camera *        OSGTestSceneItemBase::_sfCamera
    
*/

/*! \var std::string     OSGTestSceneItemBase::_sfActiveCamera
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<OSGTestSceneItem *, nsVCoRE>::_type(
    "OSGTestSceneItemPtr", 
    "ItemPtr", 
    OSGTestSceneItem::getClassType(),
    nsVCoRE);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(OSGTestSceneItem *, nsVCoRE)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           OSGTestSceneItem *,
                           nsVCoRE);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           OSGTestSceneItem *,
                           nsVCoRE);

OSG_END_NAMESPACE

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

void OSGTestSceneItemBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new MFString::Description(
        MFString::getClassType(),
        "url",
        "",
        UrlFieldId, UrlFieldMask,
        false,
        (Field::MFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&OSGTestSceneItem::editHandleUrl),
        static_cast<FieldGetMethodSig >(&OSGTestSceneItem::getHandleUrl));

    oType.addInitialDesc(pDesc);

    pDesc = new SFString::Description(
        SFString::getClassType(),
        "matchedUrl",
        "",
        MatchedUrlFieldId, MatchedUrlFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&OSGTestSceneItem::editHandleMatchedUrl),
        static_cast<FieldGetMethodSig >(&OSGTestSceneItem::getHandleMatchedUrl));

    oType.addInitialDesc(pDesc);

    pDesc = new SFUnrecNodePtr::Description(
        SFUnrecNodePtr::getClassType(),
        "root",
        "",
        RootFieldId, RootFieldMask,
        true,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&OSGTestSceneItem::editHandleRoot),
        static_cast<FieldGetMethodSig >(&OSGTestSceneItem::getHandleRoot));

    oType.addInitialDesc(pDesc);

    pDesc = new MFRecFieldContainerPtr::Description(
        MFRecFieldContainerPtr::getClassType(),
        "globals",
        "",
        GlobalsFieldId, GlobalsFieldMask,
        false,
        (Field::MFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&OSGTestSceneItem::editHandleGlobals),
        static_cast<FieldGetMethodSig >(&OSGTestSceneItem::getHandleGlobals));

    oType.addInitialDesc(pDesc);

    pDesc = new MFString::Description(
        MFString::getClassType(),
        "globalUrl",
        "",
        GlobalUrlFieldId, GlobalUrlFieldMask,
        false,
        (Field::MFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&OSGTestSceneItem::editHandleGlobalUrl),
        static_cast<FieldGetMethodSig >(&OSGTestSceneItem::getHandleGlobalUrl));

    oType.addInitialDesc(pDesc);

    pDesc = new SFString::Description(
        SFString::getClassType(),
        "matchedGlobalUrl",
        "",
        MatchedGlobalUrlFieldId, MatchedGlobalUrlFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&OSGTestSceneItem::editHandleMatchedGlobalUrl),
        static_cast<FieldGetMethodSig >(&OSGTestSceneItem::getHandleMatchedGlobalUrl));

    oType.addInitialDesc(pDesc);

    pDesc = new SFUnrecCameraPtr::Description(
        SFUnrecCameraPtr::getClassType(),
        "camera",
        "",
        CameraFieldId, CameraFieldMask,
        true,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&OSGTestSceneItem::editHandleCamera),
        static_cast<FieldGetMethodSig >(&OSGTestSceneItem::getHandleCamera));

    oType.addInitialDesc(pDesc);

    pDesc = new SFString::Description(
        SFString::getClassType(),
        "activeCamera",
        "",
        ActiveCameraFieldId, ActiveCameraFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&OSGTestSceneItem::editHandleActiveCamera),
        static_cast<FieldGetMethodSig >(&OSGTestSceneItem::getHandleActiveCamera));

    oType.addInitialDesc(pDesc);
}


OSGTestSceneItemBase::TypeObject OSGTestSceneItemBase::_type(
    OSGTestSceneItemBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsVCoRE, //Namespace
    reinterpret_cast<PrototypeCreateF>(&OSGTestSceneItemBase::createEmptyLocal),
    OSGTestSceneItem::initMethod,
    OSGTestSceneItem::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&OSGTestSceneItem::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\" ?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"OSGTestSceneItem\"\n"
    "    parent=\"Item\"\n"
    "    library=\"VCoRETest\"\n"
    "    structure=\"concrete\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    isNodeCore=\"false\"\n"
    "    isBundle=\"true\"\n"
    "    docGroupBase=\"GrpVCoreSystem\"\n"
    "    libnamespace=\"VCoRE\"\n"
    "    >\n"
    "  <Field\n"
    "      name=\"url\"\n"
    "      type=\"std::string\"\n"
    "      cardinality=\"multi\"\n"
    "      visibility=\"external\"\n"
    "      access=\"public\"\n"
    "      >\n"
    "  </Field>\n"
    "  <Field\n"
    "      name=\"matchedUrl\"\n"
    "      type=\"std::string\"\n"
    "      cardinality=\"single\"\n"
    "      visibility=\"external\"\n"
    "      access=\"public\"\n"
    "      >\n"
    "  </Field>\n"
    "  <Field\n"
    "\t name=\"root\"\n"
    "\t type=\"Node\"\n"
    "\t cardinality=\"single\"\n"
    "\t visibility=\"internal\"\n"
    "\t defaultValue=\"NULL\"\n"
    "\t access=\"public\"\n"
    "     category=\"pointer\"\n"
    "\t >\n"
    "  </Field>\n"
    "\n"
    "  <Field\n"
    "      name=\"globals\"\n"
    "      type=\"FieldContainer\"\n"
    "      cardinality=\"multi\"\n"
    "      visibility=\"external\"\n"
    "      access=\"public\"\n"
    "      category=\"recpointer\"\n"
    "      >\n"
    "  </Field>\n"
    "  <Field\n"
    "      name=\"globalUrl\"\n"
    "      type=\"std::string\"\n"
    "      cardinality=\"multi\"\n"
    "      visibility=\"external\"\n"
    "      access=\"public\"\n"
    "      >\n"
    "  </Field>\n"
    "  <Field\n"
    "      name=\"matchedGlobalUrl\"\n"
    "      type=\"std::string\"\n"
    "      cardinality=\"single\"\n"
    "      visibility=\"external\"\n"
    "      access=\"public\"\n"
    "      >\n"
    "  </Field>\n"
    "\n"
    "  <Field\n"
    "\t name=\"camera\"\n"
    "\t type=\"Camera\"\n"
    "\t cardinality=\"single\"\n"
    "\t visibility=\"internal\"\n"
    "\t defaultValue=\"NULL\"\n"
    "\t access=\"public\"\n"
    "     category=\"pointer\"\n"
    "\t >\n"
    "  </Field>\n"
    "\n"
    "  <Field\n"
    "      name=\"activeCamera\"\n"
    "      type=\"std::string\"\n"
    "      cardinality=\"single\"\n"
    "      visibility=\"external\"\n"
    "      access=\"public\"\n"
    "      >\n"
    "  </Field>\n"
    "\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &OSGTestSceneItemBase::getType(void)
{
    return _type;
}

const FieldContainerType &OSGTestSceneItemBase::getType(void) const
{
    return _type;
}

UInt32 OSGTestSceneItemBase::getContainerSize(void) const
{
    return sizeof(OSGTestSceneItem);
}

/*------------------------- decorator get ------------------------------*/


MFString *OSGTestSceneItemBase::editMFUrl(void)
{
    editMField(UrlFieldMask, _mfUrl);

    return &_mfUrl;
}

const MFString *OSGTestSceneItemBase::getMFUrl(void) const
{
    return &_mfUrl;
}


SFString *OSGTestSceneItemBase::editSFMatchedUrl(void)
{
    editSField(MatchedUrlFieldMask);

    return &_sfMatchedUrl;
}

const SFString *OSGTestSceneItemBase::getSFMatchedUrl(void) const
{
    return &_sfMatchedUrl;
}


//! Get the OSGTestSceneItem::_sfRoot field.
const SFUnrecNodePtr *OSGTestSceneItemBase::getSFRoot(void) const
{
    return &_sfRoot;
}

SFUnrecNodePtr      *OSGTestSceneItemBase::editSFRoot           (void)
{
    editSField(RootFieldMask);

    return &_sfRoot;
}

//! Get the OSGTestSceneItem::_mfGlobals field.
const MFRecFieldContainerPtr *OSGTestSceneItemBase::getMFGlobals(void) const
{
    return &_mfGlobals;
}

MFRecFieldContainerPtr *OSGTestSceneItemBase::editMFGlobals        (void)
{
    editMField(GlobalsFieldMask, _mfGlobals);

    return &_mfGlobals;
}

MFString *OSGTestSceneItemBase::editMFGlobalUrl(void)
{
    editMField(GlobalUrlFieldMask, _mfGlobalUrl);

    return &_mfGlobalUrl;
}

const MFString *OSGTestSceneItemBase::getMFGlobalUrl(void) const
{
    return &_mfGlobalUrl;
}


SFString *OSGTestSceneItemBase::editSFMatchedGlobalUrl(void)
{
    editSField(MatchedGlobalUrlFieldMask);

    return &_sfMatchedGlobalUrl;
}

const SFString *OSGTestSceneItemBase::getSFMatchedGlobalUrl(void) const
{
    return &_sfMatchedGlobalUrl;
}


//! Get the OSGTestSceneItem::_sfCamera field.
const SFUnrecCameraPtr *OSGTestSceneItemBase::getSFCamera(void) const
{
    return &_sfCamera;
}

SFUnrecCameraPtr    *OSGTestSceneItemBase::editSFCamera         (void)
{
    editSField(CameraFieldMask);

    return &_sfCamera;
}

SFString *OSGTestSceneItemBase::editSFActiveCamera(void)
{
    editSField(ActiveCameraFieldMask);

    return &_sfActiveCamera;
}

const SFString *OSGTestSceneItemBase::getSFActiveCamera(void) const
{
    return &_sfActiveCamera;
}




void OSGTestSceneItemBase::pushToGlobals(FieldContainer * const value)
{
    editMField(GlobalsFieldMask, _mfGlobals);

    _mfGlobals.push_back(value);
}

void OSGTestSceneItemBase::assignGlobals  (const MFRecFieldContainerPtr &value)
{
    MFRecFieldContainerPtr::const_iterator elemIt  =
        value.begin();
    MFRecFieldContainerPtr::const_iterator elemEnd =
        value.end  ();

    static_cast<OSGTestSceneItem *>(this)->clearGlobals();

    while(elemIt != elemEnd)
    {
        this->pushToGlobals(*elemIt);

        ++elemIt;
    }
}

void OSGTestSceneItemBase::removeFromGlobals(UInt32 uiIndex)
{
    if(uiIndex < _mfGlobals.size())
    {
        editMField(GlobalsFieldMask, _mfGlobals);

        _mfGlobals.erase(uiIndex);
    }
}

void OSGTestSceneItemBase::removeObjFromGlobals(FieldContainer * const value)
{
    Int32 iElemIdx = _mfGlobals.findIndex(value);

    if(iElemIdx != -1)
    {
        editMField(GlobalsFieldMask, _mfGlobals);

        _mfGlobals.erase(iElemIdx);
    }
}
void OSGTestSceneItemBase::clearGlobals(void)
{
    editMField(GlobalsFieldMask, _mfGlobals);


    _mfGlobals.clear();
}



/*------------------------------ access -----------------------------------*/

SizeT OSGTestSceneItemBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (UrlFieldMask & whichField))
    {
        returnValue += _mfUrl.getBinSize();
    }
    if(FieldBits::NoField != (MatchedUrlFieldMask & whichField))
    {
        returnValue += _sfMatchedUrl.getBinSize();
    }
    if(FieldBits::NoField != (RootFieldMask & whichField))
    {
        returnValue += _sfRoot.getBinSize();
    }
    if(FieldBits::NoField != (GlobalsFieldMask & whichField))
    {
        returnValue += _mfGlobals.getBinSize();
    }
    if(FieldBits::NoField != (GlobalUrlFieldMask & whichField))
    {
        returnValue += _mfGlobalUrl.getBinSize();
    }
    if(FieldBits::NoField != (MatchedGlobalUrlFieldMask & whichField))
    {
        returnValue += _sfMatchedGlobalUrl.getBinSize();
    }
    if(FieldBits::NoField != (CameraFieldMask & whichField))
    {
        returnValue += _sfCamera.getBinSize();
    }
    if(FieldBits::NoField != (ActiveCameraFieldMask & whichField))
    {
        returnValue += _sfActiveCamera.getBinSize();
    }

    return returnValue;
}

void OSGTestSceneItemBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (UrlFieldMask & whichField))
    {
        _mfUrl.copyToBin(pMem);
    }
    if(FieldBits::NoField != (MatchedUrlFieldMask & whichField))
    {
        _sfMatchedUrl.copyToBin(pMem);
    }
    if(FieldBits::NoField != (RootFieldMask & whichField))
    {
        _sfRoot.copyToBin(pMem);
    }
    if(FieldBits::NoField != (GlobalsFieldMask & whichField))
    {
        _mfGlobals.copyToBin(pMem);
    }
    if(FieldBits::NoField != (GlobalUrlFieldMask & whichField))
    {
        _mfGlobalUrl.copyToBin(pMem);
    }
    if(FieldBits::NoField != (MatchedGlobalUrlFieldMask & whichField))
    {
        _sfMatchedGlobalUrl.copyToBin(pMem);
    }
    if(FieldBits::NoField != (CameraFieldMask & whichField))
    {
        _sfCamera.copyToBin(pMem);
    }
    if(FieldBits::NoField != (ActiveCameraFieldMask & whichField))
    {
        _sfActiveCamera.copyToBin(pMem);
    }
}

void OSGTestSceneItemBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (UrlFieldMask & whichField))
    {
        editMField(UrlFieldMask, _mfUrl);
        _mfUrl.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (MatchedUrlFieldMask & whichField))
    {
        editSField(MatchedUrlFieldMask);
        _sfMatchedUrl.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (RootFieldMask & whichField))
    {
        editSField(RootFieldMask);
        _sfRoot.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (GlobalsFieldMask & whichField))
    {
        editMField(GlobalsFieldMask, _mfGlobals);
        _mfGlobals.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (GlobalUrlFieldMask & whichField))
    {
        editMField(GlobalUrlFieldMask, _mfGlobalUrl);
        _mfGlobalUrl.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (MatchedGlobalUrlFieldMask & whichField))
    {
        editSField(MatchedGlobalUrlFieldMask);
        _sfMatchedGlobalUrl.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (CameraFieldMask & whichField))
    {
        editSField(CameraFieldMask);
        _sfCamera.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (ActiveCameraFieldMask & whichField))
    {
        editSField(ActiveCameraFieldMask);
        _sfActiveCamera.copyFromBin(pMem);
    }
}

//! create a new instance of the class
OSGTestSceneItemTransitPtr OSGTestSceneItemBase::createLocal(BitVector bFlags)
{
    OSGTestSceneItemTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<OSGTestSceneItem>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
OSGTestSceneItemTransitPtr OSGTestSceneItemBase::createDependent(BitVector bFlags)
{
    OSGTestSceneItemTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<OSGTestSceneItem>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
OSGTestSceneItemTransitPtr OSGTestSceneItemBase::create(void)
{
    return createLocal();
}

OSGTestSceneItem *OSGTestSceneItemBase::createEmptyLocal(BitVector bFlags)
{
    OSGTestSceneItem *returnValue;

    newPtr<OSGTestSceneItem>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
OSGTestSceneItem *OSGTestSceneItemBase::createEmpty(void)
{
    return createEmptyLocal();
}


FieldContainerTransitPtr OSGTestSceneItemBase::shallowCopyLocal(
    BitVector bFlags) const
{
    OSGTestSceneItem *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const OSGTestSceneItem *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr OSGTestSceneItemBase::shallowCopyDependent(
    BitVector bFlags) const
{
    OSGTestSceneItem *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const OSGTestSceneItem *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr OSGTestSceneItemBase::shallowCopy(void) const
{
    return shallowCopyLocal();
}




/*------------------------- constructors ----------------------------------*/

OSGTestSceneItemBase::OSGTestSceneItemBase(void) :
    Inherited(),
    _mfUrl                    (),
    _sfMatchedUrl             (),
    _sfRoot                   (NULL),
    _mfGlobals                (),
    _mfGlobalUrl              (),
    _sfMatchedGlobalUrl       (),
    _sfCamera                 (NULL),
    _sfActiveCamera           ()
{
}

OSGTestSceneItemBase::OSGTestSceneItemBase(const OSGTestSceneItemBase &source) :
    Inherited(source),
    _mfUrl                    (source._mfUrl                    ),
    _sfMatchedUrl             (source._sfMatchedUrl             ),
    _sfRoot                   (NULL),
    _mfGlobals                (),
    _mfGlobalUrl              (source._mfGlobalUrl              ),
    _sfMatchedGlobalUrl       (source._sfMatchedGlobalUrl       ),
    _sfCamera                 (NULL),
    _sfActiveCamera           (source._sfActiveCamera           )
{
}


/*-------------------------- destructors ----------------------------------*/

OSGTestSceneItemBase::~OSGTestSceneItemBase(void)
{
}

void OSGTestSceneItemBase::onCreate(const OSGTestSceneItem *source)
{
    Inherited::onCreate(source);

    if(source != NULL)
    {
        OSGTestSceneItem *pThis = static_cast<OSGTestSceneItem *>(this);

        pThis->setRoot(source->getRoot());

        MFRecFieldContainerPtr::const_iterator GlobalsIt  =
            source->_mfGlobals.begin();
        MFRecFieldContainerPtr::const_iterator GlobalsEnd =
            source->_mfGlobals.end  ();

        while(GlobalsIt != GlobalsEnd)
        {
            pThis->pushToGlobals(*GlobalsIt);

            ++GlobalsIt;
        }

        pThis->setCamera(source->getCamera());
    }
}

GetFieldHandlePtr OSGTestSceneItemBase::getHandleUrl             (void) const
{
    MFString::GetHandlePtr returnValue(
        new  MFString::GetHandle(
             &_mfUrl,
             this->getType().getFieldDesc(UrlFieldId),
             const_cast<OSGTestSceneItemBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr OSGTestSceneItemBase::editHandleUrl            (void)
{
    MFString::EditHandlePtr returnValue(
        new  MFString::EditHandle(
             &_mfUrl,
             this->getType().getFieldDesc(UrlFieldId),
             this));


    editMField(UrlFieldMask, _mfUrl);

    return returnValue;
}

GetFieldHandlePtr OSGTestSceneItemBase::getHandleMatchedUrl      (void) const
{
    SFString::GetHandlePtr returnValue(
        new  SFString::GetHandle(
             &_sfMatchedUrl,
             this->getType().getFieldDesc(MatchedUrlFieldId),
             const_cast<OSGTestSceneItemBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr OSGTestSceneItemBase::editHandleMatchedUrl     (void)
{
    SFString::EditHandlePtr returnValue(
        new  SFString::EditHandle(
             &_sfMatchedUrl,
             this->getType().getFieldDesc(MatchedUrlFieldId),
             this));


    editSField(MatchedUrlFieldMask);

    return returnValue;
}

GetFieldHandlePtr OSGTestSceneItemBase::getHandleRoot            (void) const
{
    SFUnrecNodePtr::GetHandlePtr returnValue(
        new  SFUnrecNodePtr::GetHandle(
             &_sfRoot,
             this->getType().getFieldDesc(RootFieldId),
             const_cast<OSGTestSceneItemBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr OSGTestSceneItemBase::editHandleRoot           (void)
{
    SFUnrecNodePtr::EditHandlePtr returnValue(
        new  SFUnrecNodePtr::EditHandle(
             &_sfRoot,
             this->getType().getFieldDesc(RootFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&OSGTestSceneItem::setRoot,
                    static_cast<OSGTestSceneItem *>(this), _1));

    editSField(RootFieldMask);

    return returnValue;
}

GetFieldHandlePtr OSGTestSceneItemBase::getHandleGlobals         (void) const
{
    MFRecFieldContainerPtr::GetHandlePtr returnValue(
        new  MFRecFieldContainerPtr::GetHandle(
             &_mfGlobals,
             this->getType().getFieldDesc(GlobalsFieldId),
             const_cast<OSGTestSceneItemBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr OSGTestSceneItemBase::editHandleGlobals        (void)
{
    MFRecFieldContainerPtr::EditHandlePtr returnValue(
        new  MFRecFieldContainerPtr::EditHandle(
             &_mfGlobals,
             this->getType().getFieldDesc(GlobalsFieldId),
             this));

    returnValue->setAddMethod(
        boost::bind(&OSGTestSceneItem::pushToGlobals,
                    static_cast<OSGTestSceneItem *>(this), _1));
    returnValue->setRemoveMethod(
        boost::bind(&OSGTestSceneItem::removeFromGlobals,
                    static_cast<OSGTestSceneItem *>(this), _1));
    returnValue->setRemoveObjMethod(
        boost::bind(&OSGTestSceneItem::removeObjFromGlobals,
                    static_cast<OSGTestSceneItem *>(this), _1));
    returnValue->setClearMethod(
        boost::bind(&OSGTestSceneItem::clearGlobals,
                    static_cast<OSGTestSceneItem *>(this)));

    editMField(GlobalsFieldMask, _mfGlobals);

    return returnValue;
}

GetFieldHandlePtr OSGTestSceneItemBase::getHandleGlobalUrl       (void) const
{
    MFString::GetHandlePtr returnValue(
        new  MFString::GetHandle(
             &_mfGlobalUrl,
             this->getType().getFieldDesc(GlobalUrlFieldId),
             const_cast<OSGTestSceneItemBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr OSGTestSceneItemBase::editHandleGlobalUrl      (void)
{
    MFString::EditHandlePtr returnValue(
        new  MFString::EditHandle(
             &_mfGlobalUrl,
             this->getType().getFieldDesc(GlobalUrlFieldId),
             this));


    editMField(GlobalUrlFieldMask, _mfGlobalUrl);

    return returnValue;
}

GetFieldHandlePtr OSGTestSceneItemBase::getHandleMatchedGlobalUrl (void) const
{
    SFString::GetHandlePtr returnValue(
        new  SFString::GetHandle(
             &_sfMatchedGlobalUrl,
             this->getType().getFieldDesc(MatchedGlobalUrlFieldId),
             const_cast<OSGTestSceneItemBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr OSGTestSceneItemBase::editHandleMatchedGlobalUrl(void)
{
    SFString::EditHandlePtr returnValue(
        new  SFString::EditHandle(
             &_sfMatchedGlobalUrl,
             this->getType().getFieldDesc(MatchedGlobalUrlFieldId),
             this));


    editSField(MatchedGlobalUrlFieldMask);

    return returnValue;
}

GetFieldHandlePtr OSGTestSceneItemBase::getHandleCamera          (void) const
{
    SFUnrecCameraPtr::GetHandlePtr returnValue(
        new  SFUnrecCameraPtr::GetHandle(
             &_sfCamera,
             this->getType().getFieldDesc(CameraFieldId),
             const_cast<OSGTestSceneItemBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr OSGTestSceneItemBase::editHandleCamera         (void)
{
    SFUnrecCameraPtr::EditHandlePtr returnValue(
        new  SFUnrecCameraPtr::EditHandle(
             &_sfCamera,
             this->getType().getFieldDesc(CameraFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&OSGTestSceneItem::setCamera,
                    static_cast<OSGTestSceneItem *>(this), _1));

    editSField(CameraFieldMask);

    return returnValue;
}

GetFieldHandlePtr OSGTestSceneItemBase::getHandleActiveCamera    (void) const
{
    SFString::GetHandlePtr returnValue(
        new  SFString::GetHandle(
             &_sfActiveCamera,
             this->getType().getFieldDesc(ActiveCameraFieldId),
             const_cast<OSGTestSceneItemBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr OSGTestSceneItemBase::editHandleActiveCamera   (void)
{
    SFString::EditHandlePtr returnValue(
        new  SFString::EditHandle(
             &_sfActiveCamera,
             this->getType().getFieldDesc(ActiveCameraFieldId),
             this));


    editSField(ActiveCameraFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void OSGTestSceneItemBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    OSGTestSceneItem *pThis = static_cast<OSGTestSceneItem *>(this);

    pThis->execSync(static_cast<OSGTestSceneItem *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *OSGTestSceneItemBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    OSGTestSceneItem *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const OSGTestSceneItem *>(pRefAspect),
                  dynamic_cast<const OSGTestSceneItem *>(this));

    return returnValue;
}
#endif

void OSGTestSceneItemBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<OSGTestSceneItem *>(this)->setRoot(NULL);

    static_cast<OSGTestSceneItem *>(this)->clearGlobals();

    static_cast<OSGTestSceneItem *>(this)->setCamera(NULL);

#ifdef OSG_MT_CPTR_ASPECT
    AspectOffsetStore oOffsets;

    _pAspectStore->fillOffsetArray(oOffsets, this);
#endif

#ifdef OSG_MT_CPTR_ASPECT
    _mfUrl.terminateShare(Thread::getCurrentAspect(),
                                      oOffsets);
#endif
#ifdef OSG_MT_CPTR_ASPECT
    _mfGlobalUrl.terminateShare(Thread::getCurrentAspect(),
                                      oOffsets);
#endif
}


VCORE_END_NAMESPACE
