/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGOSGTESTSCENEITEMFIELDS_H_
#define _OSGOSGTESTSCENEITEMFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGVCoRETestDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

class OSGTestSceneItem;

OSG_GEN_CONTAINERPTR(OSGTestSceneItem);

VCORE_END_NAMESPACE

OSG_BEGIN_NAMESPACE

VCORE_IMPORT_NAMESPACE;
/*! \ingroup GrpVCoreSystemFieldTraits
    \ingroup GrpLibOSGVCoRETest
 */
template <>
struct FieldTraits<OSGTestSceneItem *, nsVCoRE> :
    public FieldTraitsFCPtrBase<OSGTestSceneItem *, nsVCoRE>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<OSGTestSceneItem *, nsVCoRE>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCORETEST_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<OSGTestSceneItem *, nsVCoRE>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecOSGTestSceneItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<OSGTestSceneItem *, nsVCoRE>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecOSGTestSceneItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<OSGTestSceneItem *, nsVCoRE>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakOSGTestSceneItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<OSGTestSceneItem *, nsVCoRE>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdOSGTestSceneItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<OSGTestSceneItem *, nsVCoRE>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecOSGTestSceneItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<OSGTestSceneItem *, nsVCoRE>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecOSGTestSceneItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<OSGTestSceneItem *, nsVCoRE>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakOSGTestSceneItemPtr"; 
}

template<> inline
const Char8 *FieldTraits<OSGTestSceneItem *, nsVCoRE>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdOSGTestSceneItemPtr"; 
}


OSG_END_NAMESPACE

VCORE_BEGIN_NAMESPACE

OSG_IMPORT_NAMESPACE;

#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<OSGTestSceneItem *,
                      RecordedRefCountPolicy, nsVCoRE  > SFRecOSGTestSceneItemPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<OSGTestSceneItem *,
                      UnrecordedRefCountPolicy, nsVCoRE> SFUnrecOSGTestSceneItemPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<OSGTestSceneItem *,
                      WeakRefCountPolicy, nsVCoRE      > SFWeakOSGTestSceneItemPtr;
/*! \ingroup GrpVCoreSystemFieldSFields */
typedef PointerSField<OSGTestSceneItem *,
                      NoRefCountPolicy, nsVCoRE        > SFUncountedOSGTestSceneItemPtr;


/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<OSGTestSceneItem *,
                      RecordedRefCountPolicy, nsVCoRE  > MFRecOSGTestSceneItemPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<OSGTestSceneItem *,
                      UnrecordedRefCountPolicy, nsVCoRE> MFUnrecOSGTestSceneItemPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<OSGTestSceneItem *,
                      WeakRefCountPolicy, nsVCoRE      > MFWeakOSGTestSceneItemPtr;
/*! \ingroup GrpVCoreSystemFieldMFields */
typedef PointerMField<OSGTestSceneItem *,
                      NoRefCountPolicy, nsVCoRE        > MFUncountedOSGTestSceneItemPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoRETest */
struct SFRecOSGTestSceneItemPtr : 
    public PointerSField<OSGTestSceneItem *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoRETest */
struct SFUnrecOSGTestSceneItemPtr : 
    public PointerSField<OSGTestSceneItem *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoRETest */
struct SFWeakOSGTestSceneItemPtr :
    public PointerSField<OSGTestSceneItem *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldSFields \ingroup GrpLibOSGVCoRETest */
struct SFUncountedOSGTestSceneItemPtr :
    public PointerSField<OSGTestSceneItem *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoRETest */
struct MFRecOSGTestSceneItemPtr :
    public PointerMField<OSGTestSceneItem *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoRETest */
struct MFUnrecOSGTestSceneItemPtr :
    public PointerMField<OSGTestSceneItem *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoRETest */
struct MFWeakOSGTestSceneItemPtr :
    public PointerMField<OSGTestSceneItem *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVCoreSystemFieldMFields \ingroup GrpLibOSGVCoRETest */
struct MFUncountedOSGTestSceneItemPtr :
    public PointerMField<OSGTestSceneItem *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

VCORE_END_NAMESPACE

#endif /* _OSGOSGTESTSCENEITEMFIELDS_H_ */
