/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGVCRENDERERFIELDS_H_
#define _OSGVCRENDERERFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGVCoreRendererDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class VCRenderer;

OSG_GEN_CONTAINERPTR(VCRenderer);

/*! \ingroup GrpVCoreRendererFieldTraits
    \ingroup GrpLibOSGVCoreRenderer
 */
template <>
struct FieldTraits<VCRenderer *> :
    public FieldTraitsFCPtrBase<VCRenderer *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<VCRenderer *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCORERENDERER_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFVCRendererPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFVCRendererPtr"; }
};

template<> inline
const Char8 *FieldTraits<VCRenderer *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecVCRendererPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCRenderer *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecVCRendererPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCRenderer *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakVCRendererPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCRenderer *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdVCRendererPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCRenderer *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecVCRendererPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCRenderer *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecVCRendererPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCRenderer *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakVCRendererPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCRenderer *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdVCRendererPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVCoreRendererFieldSFields */
typedef PointerSField<VCRenderer *,
                      RecordedRefCountPolicy  > SFRecVCRendererPtr;
/*! \ingroup GrpVCoreRendererFieldSFields */
typedef PointerSField<VCRenderer *,
                      UnrecordedRefCountPolicy> SFUnrecVCRendererPtr;
/*! \ingroup GrpVCoreRendererFieldSFields */
typedef PointerSField<VCRenderer *,
                      WeakRefCountPolicy      > SFWeakVCRendererPtr;
/*! \ingroup GrpVCoreRendererFieldSFields */
typedef PointerSField<VCRenderer *,
                      NoRefCountPolicy        > SFUncountedVCRendererPtr;


/*! \ingroup GrpVCoreRendererFieldMFields */
typedef PointerMField<VCRenderer *,
                      RecordedRefCountPolicy  > MFRecVCRendererPtr;
/*! \ingroup GrpVCoreRendererFieldMFields */
typedef PointerMField<VCRenderer *,
                      UnrecordedRefCountPolicy> MFUnrecVCRendererPtr;
/*! \ingroup GrpVCoreRendererFieldMFields */
typedef PointerMField<VCRenderer *,
                      WeakRefCountPolicy      > MFWeakVCRendererPtr;
/*! \ingroup GrpVCoreRendererFieldMFields */
typedef PointerMField<VCRenderer *,
                      NoRefCountPolicy        > MFUncountedVCRendererPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpVCoreRendererFieldSFields \ingroup GrpLibOSGVCoreRenderer */
struct SFRecVCRendererPtr : 
    public PointerSField<VCRenderer *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreRendererFieldSFields \ingroup GrpLibOSGVCoreRenderer */
struct SFUnrecVCRendererPtr : 
    public PointerSField<VCRenderer *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreRendererFieldSFields \ingroup GrpLibOSGVCoreRenderer */
struct SFWeakVCRendererPtr :
    public PointerSField<VCRenderer *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVCoreRendererFieldSFields \ingroup GrpLibOSGVCoreRenderer */
struct SFUncountedVCRendererPtr :
    public PointerSField<VCRenderer *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVCoreRendererFieldMFields \ingroup GrpLibOSGVCoreRenderer */
struct MFRecVCRendererPtr :
    public PointerMField<VCRenderer *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVCoreRendererFieldMFields \ingroup GrpLibOSGVCoreRenderer */
struct MFUnrecVCRendererPtr :
    public PointerMField<VCRenderer *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreRendererFieldMFields \ingroup GrpLibOSGVCoreRenderer */
struct MFWeakVCRendererPtr :
    public PointerMField<VCRenderer *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVCoreRendererFieldMFields \ingroup GrpLibOSGVCoreRenderer */
struct MFUncountedVCRendererPtr :
    public PointerMField<VCRenderer *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGVCRENDERERFIELDS_H_ */
