/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGVCRENDERTASKFIELDS_H_
#define _OSGVCRENDERTASKFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGVCoreRendererDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class VCRenderTask;

OSG_GEN_CONTAINERPTR(VCRenderTask);

/*! \ingroup GrpVCoreRendererFieldTraits
    \ingroup GrpLibOSGVCoreRenderer
 */
template <>
struct FieldTraits<VCRenderTask *> :
    public FieldTraitsFCPtrBase<VCRenderTask *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<VCRenderTask *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_VCORERENDERER_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFVCRenderTaskPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFVCRenderTaskPtr"; }
};

template<> inline
const Char8 *FieldTraits<VCRenderTask *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecVCRenderTaskPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCRenderTask *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecVCRenderTaskPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCRenderTask *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakVCRenderTaskPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCRenderTask *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdVCRenderTaskPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCRenderTask *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecVCRenderTaskPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCRenderTask *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecVCRenderTaskPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCRenderTask *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakVCRenderTaskPtr"; 
}

template<> inline
const Char8 *FieldTraits<VCRenderTask *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdVCRenderTaskPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpVCoreRendererFieldSFields */
typedef PointerSField<VCRenderTask *,
                      RecordedRefCountPolicy  > SFRecVCRenderTaskPtr;
/*! \ingroup GrpVCoreRendererFieldSFields */
typedef PointerSField<VCRenderTask *,
                      UnrecordedRefCountPolicy> SFUnrecVCRenderTaskPtr;
/*! \ingroup GrpVCoreRendererFieldSFields */
typedef PointerSField<VCRenderTask *,
                      WeakRefCountPolicy      > SFWeakVCRenderTaskPtr;
/*! \ingroup GrpVCoreRendererFieldSFields */
typedef PointerSField<VCRenderTask *,
                      NoRefCountPolicy        > SFUncountedVCRenderTaskPtr;


/*! \ingroup GrpVCoreRendererFieldMFields */
typedef PointerMField<VCRenderTask *,
                      RecordedRefCountPolicy  > MFRecVCRenderTaskPtr;
/*! \ingroup GrpVCoreRendererFieldMFields */
typedef PointerMField<VCRenderTask *,
                      UnrecordedRefCountPolicy> MFUnrecVCRenderTaskPtr;
/*! \ingroup GrpVCoreRendererFieldMFields */
typedef PointerMField<VCRenderTask *,
                      WeakRefCountPolicy      > MFWeakVCRenderTaskPtr;
/*! \ingroup GrpVCoreRendererFieldMFields */
typedef PointerMField<VCRenderTask *,
                      NoRefCountPolicy        > MFUncountedVCRenderTaskPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpVCoreRendererFieldSFields \ingroup GrpLibOSGVCoreRenderer */
struct SFRecVCRenderTaskPtr : 
    public PointerSField<VCRenderTask *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreRendererFieldSFields \ingroup GrpLibOSGVCoreRenderer */
struct SFUnrecVCRenderTaskPtr : 
    public PointerSField<VCRenderTask *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreRendererFieldSFields \ingroup GrpLibOSGVCoreRenderer */
struct SFWeakVCRenderTaskPtr :
    public PointerSField<VCRenderTask *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpVCoreRendererFieldSFields \ingroup GrpLibOSGVCoreRenderer */
struct SFUncountedVCRenderTaskPtr :
    public PointerSField<VCRenderTask *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpVCoreRendererFieldMFields \ingroup GrpLibOSGVCoreRenderer */
struct MFRecVCRenderTaskPtr :
    public PointerMField<VCRenderTask *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpVCoreRendererFieldMFields \ingroup GrpLibOSGVCoreRenderer */
struct MFUnrecVCRenderTaskPtr :
    public PointerMField<VCRenderTask *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpVCoreRendererFieldMFields \ingroup GrpLibOSGVCoreRenderer */
struct MFWeakVCRenderTaskPtr :
    public PointerMField<VCRenderTask *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpVCoreRendererFieldMFields \ingroup GrpLibOSGVCoreRenderer */
struct MFUncountedVCRenderTaskPtr :
    public PointerMField<VCRenderTask *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGVCRENDERTASKFIELDS_H_ */
